import {
  School,
  User,
  AssessmentRecord,
  TermReportCard,
  AttendanceRecord,
  Assignment,
  Announcement,
  PTARecord,
  TimetableSlot,
  AuditLog,
  GradeBoundary,
  ZoomMeeting,
  DirectMessage,
  TeacherDailyDutyLog,
  StoryItem,
  SchoolGroup,
  GroupPost,
  FinancePublication
} from './types';

export const ECZ_GRADING_SCALE: GradeBoundary[] = [
  { grade: '1', label: 'Distinction', minScore: 75, maxScore: 100, points: 1 },
  { grade: '2', label: 'Distinction', minScore: 70, maxScore: 74, points: 2 },
  { grade: '3', label: 'Merit', minScore: 65, maxScore: 69, points: 3 },
  { grade: '4', label: 'Merit', minScore: 60, maxScore: 64, points: 4 },
  { grade: '5', label: 'Credit', minScore: 55, maxScore: 59, points: 5 },
  { grade: '6', label: 'Credit', minScore: 50, maxScore: 54, points: 6 },
  { grade: '7', label: 'Satisfactory', minScore: 45, maxScore: 49, points: 7 },
  { grade: '8', label: 'Satisfactory', minScore: 40, maxScore: 44, points: 8 },
  { grade: '9', label: 'Unsatisfactory', minScore: 0, maxScore: 39, points: 9 },
];

export function calculateEczGrade(percentage: number): { eczGrade: string; gradeLabel: string; points: number } {
  const rounded = Math.round(percentage);
  for (const b of ECZ_GRADING_SCALE) {
    if (rounded >= b.minScore && rounded <= b.maxScore) {
      return {
        eczGrade: b.grade,
        gradeLabel: b.label,
        points: b.points,
      };
    }
  }
  return {
    eczGrade: '9',
    gradeLabel: 'Unsatisfactory',
    points: 9,
  };
}

export const INITIAL_SCHOOLS: School[] = [
  {
    id: 'school_kabwe_tech',
    code: 'SCH-KT-1049',
    name: 'Kabwe National Technical High School',
    motto: 'Strive for Academic and Technological Excellence',
    logo: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=160&auto=format&fit=crop&q=80',
    province: 'Central Province',
    city: 'Kabwe',
    address: 'Plot 4022 Mukobeko Road, Kabwe',
    email: 'admin@kabwetech.edu.zm',
    phone: '+260 215 223400',
    registrationNumber: 'MOE/SEC/CB/1049/2026',
    staffPassword: 'KABWE-STAFF-2026',
    staffSubscription: {
      tier: 'premium',
      pricePerMonthZMW: 450,
      status: 'active',
      billingCycle: 'monthly',
      startDate: '2026-01-01',
      nextBillingDate: '2026-09-01',
      coveredStaffCount: 14,
      lastPaymentReference: 'MTN-MM-89310498',
      paymentMethod: 'mtn_money',
      features: [
        'All Medium School Management Features',
        'Advanced Analytics & Cohort Pass Rate Trends',
        'AI-Powered School & Subject Insights',
        'Advanced Academic & Performance Reports',
        'Attendance Analytics & Chronic Absenteeism Heatmaps',
        'Advanced Staff & Student Management',
        'Teacher Excel Studio & Live Video Class Tools'
      ]
    },
    academicYear: '2026',
    activeTerm: 'term_1',
    terms: [
      {
        id: 'term_1',
        name: 'Term 1 (Jan - Apr)',
        startDate: '2026-01-12',
        endDate: '2026-04-10',
        weeksCount: 13,
        isActive: true,
        test1Week: 4,
        test2Week: 8,
        test3Week: 12,
        examWeek: 13,
        midTermWeek: 7,
      },
      {
        id: 'term_2',
        name: 'Term 2 (May - Aug)',
        startDate: '2026-05-11',
        endDate: '2026-08-07',
        weeksCount: 13,
        isActive: false,
        test1Week: 4,
        test2Week: 8,
        test3Week: 12,
        examWeek: 13,
        midTermWeek: 7,
      },
      {
        id: 'term_3',
        name: 'Term 3 (Sep - Dec)',
        startDate: '2026-09-07',
        endDate: '2026-12-04',
        weeksCount: 13,
        isActive: false,
        test1Week: 4,
        test2Week: 8,
        test3Week: 12,
        examWeek: 13,
        midTermWeek: 7,
      },
    ],
    assessmentWeighting: {
      test1Weight: 15,
      test2Weight: 15,
      test3Weight: 15,
      assignmentWeight: 15,
      examWeight: 40,
    },
    gradingScale: ECZ_GRADING_SCALE,
    grades: ['8', '9', '10', '11', '12'],
    classes: [
      {
        id: 'class_9a',
        name: 'Grade 9A',
        grade: '9',
        stream: 'A',
        classTeacherId: 'user_teacher_tembo',
        classTeacherName: 'Mr. Kelvin Tembo',
        studentCount: 38,
        roomNumber: 'Block B - Room 4',
      },
      {
        id: 'class_9b',
        name: 'Grade 9B',
        grade: '9',
        stream: 'B',
        classTeacherId: 'user_teacher_lungu',
        classTeacherName: 'Ms. Grace Lungu',
        studentCount: 40,
        roomNumber: 'Block B - Room 5',
      },
      {
        id: 'class_11sci',
        name: 'Grade 11 Science',
        grade: '11',
        stream: 'Pure Science',
        classTeacherId: 'user_teacher_chanda',
        classTeacherName: 'Mr. Patrick Chanda',
        studentCount: 35,
        roomNumber: 'Science Complex Lab 2',
      },
      {
        id: 'class_12arts',
        name: 'Grade 12 Commercial & Arts',
        grade: '12',
        stream: 'Arts',
        classTeacherId: 'user_teacher_phiri',
        classTeacherName: 'Mrs. Bwalya Phiri',
        studentCount: 36,
        roomNumber: 'Main Hall West',
      },
    ],
    subjects: [
      { id: 'sub_math', name: 'Mathematics', code: 'MAT-401', category: 'Core', gradesApplicable: ['8', '9', '10', '11', '12'] },
      { id: 'sub_eng', name: 'English Language', code: 'ENG-101', category: 'Core', gradesApplicable: ['8', '9', '10', '11', '12'] },
      { id: 'sub_sci', name: 'Integrated Science', code: 'SCI-201', category: 'Sciences', gradesApplicable: ['8', '9'] },
      { id: 'sub_phy', name: 'Physics (Pure)', code: 'PHY-501', category: 'Sciences', gradesApplicable: ['10', '11', '12'] },
      { id: 'sub_chem', name: 'Chemistry', code: 'CHM-502', category: 'Sciences', gradesApplicable: ['10', '11', '12'] },
      { id: 'sub_bio', name: 'Biology', code: 'BIO-503', category: 'Sciences', gradesApplicable: ['10', '11', '12'] },
      { id: 'sub_cs', name: 'Computer Studies', code: 'CMP-301', category: 'Practical', gradesApplicable: ['8', '9', '10', '11', '12'] },
      { id: 'sub_geo', name: 'Geography', code: 'GEO-202', category: 'Humanities', gradesApplicable: ['8', '9', '10', '11', '12'] },
      { id: 'sub_civ', name: 'Civic Education', code: 'CIV-203', category: 'Humanities', gradesApplicable: ['8', '9', '10', '11', '12'] },
      { id: 'sub_bem', name: 'Icibemba (Zambian Language)', code: 'BEM-102', category: 'Languages', gradesApplicable: ['8', '9', '10', '11', '12'] },
    ],
    calendarEvents: [
      { id: 'cal_1', title: 'Official Term 1 Opening & Registration', date: '2026-01-12', weekNumber: 1, termId: 'term_1', type: 'academic' },
      { id: 'cal_2', title: 'Continuous Assessment Test 1 (CA-1)', date: '2026-02-02', weekNumber: 4, termId: 'term_1', type: 'test', description: 'Covers Syllabus Units 1 - 3' },
      { id: 'cal_3', title: 'Mid-Term Break & Academic Progress Consultations', date: '2026-02-23', weekNumber: 7, termId: 'term_1', type: 'holiday' },
      { id: 'cal_4', title: 'Continuous Assessment Test 2 (CA-2)', date: '2026-03-02', weekNumber: 8, termId: 'term_1', type: 'test', description: 'Comprehensive mid-term evaluation' },
      { id: 'cal_5', title: 'Inter-House Athletics & Cultural Gala', date: '2026-03-16', weekNumber: 10, termId: 'term_1', type: 'sports' },
      { id: 'cal_6', title: 'Continuous Assessment Test 3 (CA-3)', date: '2026-03-30', weekNumber: 12, termId: 'term_1', type: 'test', description: 'Pre-exam mock assessment' },
      { id: 'cal_7', title: 'Final Term 1 Examinations Week', date: '2026-04-06', weekNumber: 13, termId: 'term_1', type: 'exam', description: 'ECZ Mock & End of Term exams' },
      { id: 'cal_8', title: 'Annual General PTA Meeting & Report Card Day', date: '2026-04-10', weekNumber: 13, termId: 'term_1', type: 'pta' },
    ],
    passMark: 50,
    ptaDuesAmount: 450,
    currency: 'ZMW',
    createdAt: '2025-11-20',
  },
  {
    id: 'school_david_kaunda',
    code: 'SCH-DK-001',
    name: 'David Kaunda National STEM Academy',
    motto: 'Innovation, Science & National Leadership',
    logo: 'https://images.unsplash.com/photo-1562774053-701939374585?w=160&auto=format&fit=crop&q=80',
    province: 'Lusaka Province',
    city: 'Lusaka',
    address: 'Plot 104 Brentwood Drive, Longacres, Lusaka',
    email: 'principal@davidkaunda.edu.zm',
    phone: '+260 211 254190',
    registrationNumber: 'MOE/STEM/LP/001/2026',
    staffPassword: 'DK-STEM-STAFF-2026',
    academicYear: '2026',
    activeTerm: 'term_1',
    terms: [
      {
        id: 'term_1',
        name: 'Term 1 (Jan - Apr)',
        startDate: '2026-01-12',
        endDate: '2026-04-10',
        weeksCount: 13,
        isActive: true,
        test1Week: 4,
        test2Week: 8,
        test3Week: 12,
        examWeek: 13,
      },
    ],
    assessmentWeighting: {
      test1Weight: 15,
      test2Weight: 15,
      test3Weight: 15,
      assignmentWeight: 15,
      examWeight: 40,
    },
    gradingScale: ECZ_GRADING_SCALE,
    grades: ['8', '9', '10', '11', '12'],
    classes: [
      { id: 'class_dk_9a', name: 'Grade 9 STEM-Alpha', grade: '9', stream: 'Alpha', classTeacherId: 'user_teacher_tembo', classTeacherName: 'Mr. Kelvin Tembo', studentCount: 32 },
      { id: 'class_dk_10sci', name: 'Grade 10 Tech', grade: '10', stream: 'Tech', classTeacherId: 'user_teacher_chanda', classTeacherName: 'Mr. Patrick Chanda', studentCount: 30 },
    ],
    subjects: [
      { id: 'sub_math', name: 'Mathematics', code: 'MAT-401', category: 'Core', gradesApplicable: ['8', '9', '10', '11', '12'] },
      { id: 'sub_eng', name: 'English Language', code: 'ENG-101', category: 'Core', gradesApplicable: ['8', '9', '10', '11', '12'] },
      { id: 'sub_phy', name: 'Physics (Pure)', code: 'PHY-501', category: 'Sciences', gradesApplicable: ['10', '11', '12'] },
      { id: 'sub_chem', name: 'Chemistry', code: 'CHM-502', category: 'Sciences', gradesApplicable: ['10', '11', '12'] },
      { id: 'sub_cs', name: 'Computer Studies', code: 'CMP-301', category: 'Practical', gradesApplicable: ['8', '9', '10', '11', '12'] },
    ],
    calendarEvents: [],
    passMark: 50,
    ptaDuesAmount: 600,
    currency: 'ZMW',
    createdAt: '2025-12-01',
  },
  {
    id: 'school_hillcrest_tech',
    code: 'SCH-HC-042',
    name: 'Hillcrest National Technical Secondary School',
    motto: 'Facta Non Verba (Deeds Not Words)',
    logo: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=160&auto=format&fit=crop&q=80',
    province: 'Southern Province',
    city: 'Livingstone',
    address: 'Plot 88 Sichango Road, Livingstone',
    email: 'admin@hillcrest.edu.zm',
    phone: '+260 213 321800',
    registrationNumber: 'MOE/TECH/SP/042/2026',
    staffPassword: 'HILLCREST-STAFF-2026',
    staffSubscription: {
      tier: 'medium',
      pricePerMonthZMW: 400,
      status: 'active',
      billingCycle: 'monthly',
      startDate: '2026-01-01',
      nextBillingDate: '2026-09-01',
      coveredStaffCount: 12,
      lastPaymentReference: 'AIRTEL-MM-55219904',
      paymentMethod: 'airtel_money',
      features: [
        'School Management & Classes',
        'Staff & Faculty Rosters',
        'Students & Parent Profiles',
        'Subjects & Curriculum Configuration',
        'Continuous Assessment Tests (CA-1 to CA-3)',
        'Examination & Marks Gradebook',
        'Assignments & Attendance Rolls',
        'Announcements & Circulars',
        'Standard Term Report Cards'
      ]
    },
    academicYear: '2026',
    activeTerm: 'term_1',
    terms: [
      {
        id: 'term_1',
        name: 'Term 1 (Jan - Apr)',
        startDate: '2026-01-12',
        endDate: '2026-04-10',
        weeksCount: 13,
        isActive: true,
        test1Week: 4,
        test2Week: 8,
        test3Week: 12,
        examWeek: 13,
      },
    ],
    assessmentWeighting: {
      test1Weight: 15,
      test2Weight: 15,
      test3Weight: 15,
      assignmentWeight: 15,
      examWeight: 40,
    },
    gradingScale: ECZ_GRADING_SCALE,
    grades: ['8', '9', '10', '11', '12'],
    classes: [
      { id: 'class_hc_9a', name: 'Grade 9 Technical', grade: '9', stream: 'Tech', classTeacherId: 'user_teacher_tembo', classTeacherName: 'Mr. Kelvin Tembo', studentCount: 35 },
    ],
    subjects: [
      { id: 'sub_math', name: 'Mathematics', code: 'MAT-401', category: 'Core', gradesApplicable: ['8', '9', '10', '11', '12'] },
      { id: 'sub_eng', name: 'English Language', code: 'ENG-101', category: 'Core', gradesApplicable: ['8', '9', '10', '11', '12'] },
      { id: 'sub_sci', name: 'Integrated Science', code: 'SCI-201', category: 'Sciences', gradesApplicable: ['8', '9'] },
    ],
    calendarEvents: [],
    passMark: 50,
    ptaDuesAmount: 550,
    currency: 'ZMW',
    createdAt: '2025-12-10',
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'user_head_banda',
    fullName: 'Dr. Mwamba Banda',
    email: 'principal.banda@kabwetech.edu.zm',
    password: 'password123',
    role: 'head_teacher',
    userCategory: 'school_staff',
    phone: '+260 977 412099',
    whatsAppNumber: '+260 977 412099',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    schoolId: 'school_kabwe_tech',
    schoolName: 'Kabwe National Technical High School',
    verificationStatus: 'verified',
    createdAt: '2025-11-20',
  },
  {
    id: 'user_deputy_musonda',
    fullName: 'Mrs. Chileshe Musonda',
    email: 'deputy.musonda@kabwetech.edu.zm',
    password: 'password123',
    role: 'deputy_head_teacher',
    userCategory: 'school_staff',
    phone: '+260 978 554321',
    whatsAppNumber: '+260 978 554321',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80',
    schoolId: 'school_kabwe_tech',
    schoolName: 'Kabwe National Technical High School',
    verificationStatus: 'verified',
    createdAt: '2025-11-22',
  },
  {
    id: 'user_teacher_tembo',
    fullName: 'Mr. Kelvin Tembo',
    email: 'k.tembo@kabwetech.edu.zm',
    password: 'password123',
    role: 'teacher',
    userCategory: 'school_staff',
    phone: '+260 966 881234',
    whatsAppNumber: '+260 966 881234',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    coverPhotoUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800&auto=format&fit=crop&q=80',
    isFinanceTeam: true,
    financeRoleTitle: 'Senior Finance Committee Officer & Accounts Liaison',
    schoolId: 'school_kabwe_tech',
    schoolName: 'Kabwe National Technical High School',
    verificationStatus: 'verified',
    createdAt: '2025-11-25',
    teacherProfile: {
      employeeNumber: 'TS-KTH-042',
      assignedSubjectIds: ['sub_math', 'sub_cs'],
      assignedClassIds: ['class_9a', 'class_9b', 'class_11sci'],
      qualification: 'BSc. Mathematics with Education (UNZA)',
      specialization: 'Senior Mathematics & Computing',
      isFinanceTeam: true,
      financeRoleTitle: 'Senior Finance Committee Officer & Accounts Liaison',
    },
  },
  {
    id: 'user_teacher_lungu',
    fullName: 'Ms. Grace Lungu',
    email: 'g.lungu@kabwetech.edu.zm',
    password: 'password123',
    role: 'teacher',
    phone: '+260 971 334900',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80',
    schoolId: 'school_kabwe_tech',
    schoolName: 'Kabwe National Technical High School',
    verificationStatus: 'verified',
    createdAt: '2025-11-28',
    teacherProfile: {
      employeeNumber: 'TS-KTH-058',
      assignedSubjectIds: ['sub_eng', 'sub_civ'],
      assignedClassIds: ['class_9a', 'class_9b'],
      qualification: 'BA. English & Literature (CBU)',
      specialization: 'English & Civic Education',
    },
  },
  {
    id: 'user_teacher_chanda',
    fullName: 'Mr. Patrick Chanda',
    email: 'p.chanda@kabwetech.edu.zm',
    password: 'password123',
    role: 'teacher',
    phone: '+260 975 110022',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
    schoolId: 'school_kabwe_tech',
    schoolName: 'Kabwe National Technical High School',
    verificationStatus: 'verified',
    createdAt: '2025-11-30',
    teacherProfile: {
      employeeNumber: 'TS-KTH-071',
      assignedSubjectIds: ['sub_sci', 'sub_phy'],
      assignedClassIds: ['class_9a', 'class_11sci'],
      qualification: 'BSc. Physics (Mulungushi Univ)',
      specialization: 'Physical Sciences & Laboratory Practice',
    },
  },
  {
    id: 'user_teacher_phiri',
    fullName: 'Mrs. Bwalya Phiri',
    email: 'b.phiri@kabwetech.edu.zm',
    password: 'password123',
    role: 'teacher',
    phone: '+260 979 443211',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80',
    coverPhotoUrl: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&auto=format&fit=crop&q=80',
    isFinanceTeam: true,
    financeRoleTitle: 'Bursary Liaison & Audit Secretary',
    schoolId: 'school_kabwe_tech',
    schoolName: 'Kabwe National Technical High School',
    verificationStatus: 'verified',
    createdAt: '2025-12-01',
    teacherProfile: {
      employeeNumber: 'TS-KTH-084',
      assignedSubjectIds: ['sub_bio', 'sub_chem'],
      assignedClassIds: ['class_11sci', 'class_12arts'],
      qualification: 'BSc. Biological Sciences & Chemistry',
      specialization: 'Life Sciences & Organic Chemistry',
      isFinanceTeam: true,
      financeRoleTitle: 'Bursary Liaison & Audit Secretary',
    },
  },
  {
    id: 'user_student_mubita',
    fullName: 'Mubita Mweemba',
    email: 'mubita.m@student.kabwetech.edu.zm',
    password: 'password123',
    role: 'student',
    phone: '+260 974 001288',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=120&auto=format&fit=crop&q=80',
    schoolId: 'school_kabwe_tech',
    schoolName: 'Kabwe National Technical High School',
    verificationStatus: 'verified',
    createdAt: '2026-01-05',
    studentProfile: {
      studentNumber: 'STU-2026-0012',
      grade: '9',
      classId: 'class_9a',
      className: 'Grade 9A',
      guardianName: 'Mr. Joseph Mweemba',
      guardianPhone: '+260 977 654321',
      gender: 'Male',
      dateOfBirth: '2011-04-14',
      admissionDate: '2025-01-10',
    },
  },
  {
    id: 'user_student_natasha',
    fullName: 'Natasha Mulenga',
    email: 'natasha.m@student.kabwetech.edu.zm',
    password: 'password123',
    role: 'student',
    phone: '+260 976 112233',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&auto=format&fit=crop&q=80',
    schoolId: 'school_kabwe_tech',
    schoolName: 'Kabwe National Technical High School',
    verificationStatus: 'verified',
    createdAt: '2026-01-06',
    studentProfile: {
      studentNumber: 'STU-2026-0015',
      grade: '9',
      classId: 'class_9a',
      className: 'Grade 9A',
      guardianName: 'Mrs. Florence Mulenga',
      guardianPhone: '+260 978 998877',
      gender: 'Female',
      dateOfBirth: '2011-08-22',
      admissionDate: '2025-01-10',
    },
  },
  {
    id: 'user_student_dalitso',
    fullName: 'Dalitso Phiri',
    email: 'dalitso.p@student.kabwetech.edu.zm',
    password: 'password123',
    role: 'student',
    phone: '+260 973 445566',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&auto=format&fit=crop&q=80',
    schoolId: 'school_kabwe_tech',
    schoolName: 'Kabwe National Technical High School',
    verificationStatus: 'verified',
    createdAt: '2026-01-07',
    studentProfile: {
      studentNumber: 'STU-2026-0088',
      grade: '11',
      classId: 'class_11sci',
      className: 'Grade 11 Science',
      guardianName: 'Mr. Joseph Mweemba',
      guardianPhone: '+260 977 654321',
      gender: 'Male',
      dateOfBirth: '2009-02-18',
      admissionDate: '2024-01-12',
    },
  },
  {
    id: 'user_student_chimwemwe',
    fullName: 'Chimwemwe Zulu',
    email: 'chimwemwe.z@student.kabwetech.edu.zm',
    password: 'password123',
    role: 'student',
    phone: '+260 972 334455',
    avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=120&auto=format&fit=crop&q=80',
    schoolId: 'school_kabwe_tech',
    schoolName: 'Kabwe National Technical High School',
    verificationStatus: 'verified',
    createdAt: '2026-01-08',
    studentProfile: {
      studentNumber: 'STU-2026-0021',
      grade: '9',
      classId: 'class_9a',
      className: 'Grade 9A',
      gender: 'Female',
      dateOfBirth: '2011-11-03',
      admissionDate: '2025-01-10',
    },
  },
  {
    id: 'user_parent_mweemba',
    fullName: 'Mr. Joseph Mweemba',
    email: 'j.mweemba@gmail.com',
    password: 'password123',
    role: 'parent',
    userCategory: 'parent',
    phone: '+260 977 654321',
    whatsAppNumber: '+260 977 654321',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80',
    schoolId: 'school_kabwe_tech',
    schoolName: 'Kabwe National Technical High School',
    verificationStatus: 'verified',
    createdAt: '2026-01-10',
    parentSubscription: {
      tier: 'premium',
      pricePerMonthZMW: 200,
      status: 'active',
      billingCycle: 'monthly',
      startDate: '2026-01-10',
      nextBillingDate: '2026-09-10',
      lastPaymentReference: 'AIRTEL-MM-9932144',
      paymentMethod: 'airtel_money',
      features: [
        'Access to Linked Children Results & Grades',
        'Assignments, Tests (CA-1 to CA-3) & Homework',
        'Daily Real-Time Attendance Alerts & Time-stamps',
        'School Announcements & Official Circulars',
        'Advanced Academic Progress & Multi-Term Trajectory Charts',
        'AI-Powered Learning Insights & Weakness Diagnosis',
        'Detailed Printable Report Cards with Security QR',
        'Advanced Attendance & Subject-Specific Analytics'
      ]
    },
    parentProfile: {
      connectedStudentNumbers: ['STU-2026-0012', 'STU-2026-0088'],
      isPtaExecutive: true,
      occupation: 'Senior Logistics Specialist',
      nationalId: '342119/11/1',
    },
  },
  {
    id: 'user_parent_mulenga',
    fullName: 'Mrs. Florence Mulenga',
    email: 'f.mulenga@yahoo.com',
    password: 'password123',
    role: 'parent',
    userCategory: 'parent',
    phone: '+260 978 998877',
    whatsAppNumber: '+260 978 998877',
    avatarUrl: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=120&auto=format&fit=crop&q=80',
    schoolId: 'school_kabwe_tech',
    schoolName: 'Kabwe National Technical High School',
    verificationStatus: 'verified',
    createdAt: '2026-01-11',
    parentSubscription: {
      tier: 'medium',
      pricePerMonthZMW: 150,
      status: 'active',
      billingCycle: 'monthly',
      startDate: '2026-01-11',
      nextBillingDate: '2026-09-11',
      lastPaymentReference: 'MTN-MM-44102941',
      paymentMethod: 'mtn_money',
      features: [
        'Access to Linked Children Results & Grades',
        'Assignments, Tests & Homework Portal',
        'Daily Attendance Status',
        'School Announcements & Circulars',
        'Basic Academic Progress Summary'
      ]
    },
    parentProfile: {
      connectedStudentNumbers: ['STU-2026-0015'],
      isPtaExecutive: false,
      occupation: 'Chartered Accountant (ZICA)',
      nationalId: '298711/12/1',
    },
  },
  {
    id: 'user_board_mutale',
    fullName: 'Hon. Charles Mutale',
    email: 'c.mutale@schoolboard.gov.zm',
    password: 'password123',
    role: 'school_board',
    userCategory: 'school_staff',
    phone: '+260 977 220011',
    whatsAppNumber: '+260 977 220011',
    avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=120&auto=format&fit=crop&q=80',
    schoolId: 'school_kabwe_tech',
    schoolName: 'Kabwe National Technical High School',
    verificationStatus: 'verified',
    createdAt: '2025-10-15',
    boardProfile: {
      position: 'Board Chairperson',
      committee: 'Finance, Governance & Infrastructure',
      appointedYear: '2024',
    },
  },
  {
    id: 'user_platform_admin',
    fullName: 'Dr. Kasongo Chileshe',
    email: 'admin@schoollink.edu.zm',
    password: 'password123',
    role: 'platform_admin',
    userCategory: 'platform_admin',
    phone: '+260 977 100001',
    whatsAppNumber: '+260 977 100001',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    coverPhotoUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop&q=80',
    schoolId: 'school_kabwe_tech',
    schoolName: 'Platform Central Administration',
    verificationStatus: 'verified',
    createdAt: '2025-01-01',
    adminProfile: {
      superAdminId: 'PADM-ZAM-001',
      department: 'National School Management Platform Directorate',
      securityClearance: 'Level 5 (National Directorate)',
      authorizedBy: 'Ministry of Education & Platform Operations',
      contactOffice: 'Apex Tower, 7th Floor, Lusaka',
    },
  },
];

export const INITIAL_ASSESSMENTS: AssessmentRecord[] = [
  {
    id: 'ass_math_t1_9a',
    schoolId: 'school_kabwe_tech',
    classId: 'class_9a',
    className: 'Grade 9A',
    subjectId: 'sub_math',
    subjectName: 'Mathematics',
    teacherId: 'user_teacher_tembo',
    teacherName: 'Mr. Kelvin Tembo',
    termId: 'term_1',
    academicYear: '2026',
    title: 'Continuous Assessment Test 1 (CA-1): Algebra & Sets',
    type: 'test_1',
    maxScore: 20,
    date: '2026-02-04',
    weekNumber: 4,
    scores: [
      { studentId: 'user_student_mubita', studentNumber: 'STU-2026-0012', studentName: 'Mubita Mweemba', rawScore: 18, maxScore: 20, percentage: 90, remarks: 'Excellent algebraic expansion' },
      { studentId: 'user_student_natasha', studentNumber: 'STU-2026-0015', studentName: 'Natasha Mulenga', rawScore: 16, maxScore: 20, percentage: 80, remarks: 'Great working steps' },
      { studentId: 'user_student_chimwemwe', studentNumber: 'STU-2026-0021', studentName: 'Chimwemwe Zulu', rawScore: 14, maxScore: 20, percentage: 70, remarks: 'Good grasp of set notation' },
    ],
    status: 'published',
    submittedAt: '2026-02-05',
    approvedAt: '2026-02-06',
    approvedBy: 'Dr. Mwamba Banda',
    isLocked: true,
  },
  {
    id: 'ass_math_t2_9a',
    schoolId: 'school_kabwe_tech',
    classId: 'class_9a',
    className: 'Grade 9A',
    subjectId: 'sub_math',
    subjectName: 'Mathematics',
    teacherId: 'user_teacher_tembo',
    teacherName: 'Mr. Kelvin Tembo',
    termId: 'term_1',
    academicYear: '2026',
    title: 'Continuous Assessment Test 2 (CA-2): Geometry & Coordinates',
    type: 'test_2',
    maxScore: 20,
    date: '2026-03-04',
    weekNumber: 8,
    scores: [
      { studentId: 'user_student_mubita', studentNumber: 'STU-2026-0012', studentName: 'Mubita Mweemba', rawScore: 17, maxScore: 20, percentage: 85, remarks: 'Accurate construction' },
      { studentId: 'user_student_natasha', studentNumber: 'STU-2026-0015', studentName: 'Natasha Mulenga', rawScore: 19, maxScore: 20, percentage: 95, remarks: 'Distinction level geometric proofs' },
      { studentId: 'user_student_chimwemwe', studentNumber: 'STU-2026-0021', studentName: 'Chimwemwe Zulu', rawScore: 15, maxScore: 20, percentage: 75, remarks: 'Clear graph plotting' },
    ],
    status: 'published',
    submittedAt: '2026-03-05',
    approvedAt: '2026-03-06',
    approvedBy: 'Mrs. Chileshe Musonda',
    isLocked: true,
  },
  {
    id: 'ass_math_t3_9a',
    schoolId: 'school_kabwe_tech',
    classId: 'class_9a',
    className: 'Grade 9A',
    subjectId: 'sub_math',
    subjectName: 'Mathematics',
    teacherId: 'user_teacher_tembo',
    teacherName: 'Mr. Kelvin Tembo',
    termId: 'term_1',
    academicYear: '2026',
    title: 'Continuous Assessment Test 3 (CA-3): Trigonometry & Matrices',
    type: 'test_3',
    maxScore: 20,
    date: '2026-03-31',
    weekNumber: 12,
    scores: [
      { studentId: 'user_student_mubita', studentNumber: 'STU-2026-0012', studentName: 'Mubita Mweemba', rawScore: 18, maxScore: 20, percentage: 90, remarks: 'Superb matrix determinant calculation' },
      { studentId: 'user_student_natasha', studentNumber: 'STU-2026-0015', studentName: 'Natasha Mulenga', rawScore: 17, maxScore: 20, percentage: 85, remarks: 'Strong trigonometry angles' },
      { studentId: 'user_student_chimwemwe', studentNumber: 'STU-2026-0021', studentName: 'Chimwemwe Zulu', rawScore: 13, maxScore: 20, percentage: 65, remarks: 'Satisfactory review needed' },
    ],
    status: 'published',
    submittedAt: '2026-04-01',
    approvedAt: '2026-04-02',
    approvedBy: 'Dr. Mwamba Banda',
    isLocked: true,
  },
  {
    id: 'ass_math_exam_9a',
    schoolId: 'school_kabwe_tech',
    classId: 'class_9a',
    className: 'Grade 9A',
    subjectId: 'sub_math',
    subjectName: 'Mathematics',
    teacherId: 'user_teacher_tembo',
    teacherName: 'Mr. Kelvin Tembo',
    termId: 'term_1',
    academicYear: '2026',
    title: 'End of Term 1 Final Examination (Paper 1 & Paper 2)',
    type: 'examination',
    maxScore: 100,
    date: '2026-04-07',
    weekNumber: 13,
    scores: [
      { studentId: 'user_student_mubita', studentNumber: 'STU-2026-0012', studentName: 'Mubita Mweemba', rawScore: 88, maxScore: 100, percentage: 88, remarks: 'Outstanding distinction mark' },
      { studentId: 'user_student_natasha', studentNumber: 'STU-2026-0015', studentName: 'Natasha Mulenga', rawScore: 84, maxScore: 100, percentage: 84, remarks: 'Solid mastery of ECZ syllabus' },
      { studentId: 'user_student_chimwemwe', studentNumber: 'STU-2026-0021', studentName: 'Chimwemwe Zulu', rawScore: 71, maxScore: 100, percentage: 71, remarks: 'Merit score attained' },
    ],
    status: 'published',
    submittedAt: '2026-04-08',
    approvedAt: '2026-04-09',
    approvedBy: 'Dr. Mwamba Banda',
    isLocked: true,
  },
  {
    id: 'ass_eng_t1_9a',
    schoolId: 'school_kabwe_tech',
    classId: 'class_9a',
    className: 'Grade 9A',
    subjectId: 'sub_eng',
    subjectName: 'English Language',
    teacherId: 'user_teacher_lungu',
    teacherName: 'Ms. Grace Lungu',
    termId: 'term_1',
    academicYear: '2026',
    title: 'Continuous Assessment Test 1 (CA-1): Composition & Grammar',
    type: 'test_1',
    maxScore: 30,
    date: '2026-02-03',
    weekNumber: 4,
    scores: [
      { studentId: 'user_student_mubita', studentNumber: 'STU-2026-0012', studentName: 'Mubita Mweemba', rawScore: 26, maxScore: 30, percentage: 86.7, remarks: 'Rich vocabulary and structure' },
      { studentId: 'user_student_natasha', studentNumber: 'STU-2026-0015', studentName: 'Natasha Mulenga', rawScore: 28, maxScore: 30, percentage: 93.3, remarks: 'Flawless prose and punctuation' },
      { studentId: 'user_student_chimwemwe', studentNumber: 'STU-2026-0021', studentName: 'Chimwemwe Zulu', rawScore: 22, maxScore: 30, percentage: 73.3, remarks: 'Good descriptive style' },
    ],
    status: 'published',
    isLocked: true,
  },
];

export const INITIAL_REPORT_CARDS: TermReportCard[] = [
  {
    id: 'rep_mubita_t1_2026',
    schoolId: 'school_kabwe_tech',
    schoolName: 'Kabwe National Technical High School',
    studentId: 'user_student_mubita',
    studentNumber: 'STU-2026-0012',
    studentName: 'Mubita Mweemba',
    gender: 'Male',
    grade: '9',
    classId: 'class_9a',
    className: 'Grade 9A',
    termId: 'term_1',
    termName: 'Term 1',
    academicYear: '2026',
    subjectResults: [
      {
        subjectId: 'sub_math',
        subjectName: 'Mathematics',
        subjectCode: 'MAT-401',
        teacherName: 'Mr. Kelvin Tembo',
        test1Score: { raw: 18, max: 20, pct: 90 },
        test2Score: { raw: 17, max: 20, pct: 85 },
        test3Score: { raw: 18, max: 20, pct: 90 },
        assignmentAvgPct: 88,
        examScore: { raw: 88, max: 100, pct: 88 },
        totalContinuousAssessmentPct: 88.2,
        finalExamPct: 88,
        finalOverallPercentage: 88.1,
        eczGrade: '1',
        gradeLabel: 'Distinction',
        eczPoints: 1,
        teacherRemarks: 'Brilliant mathematical cognition and problem-solving initiative.',
      },
      {
        subjectId: 'sub_eng',
        subjectName: 'English Language',
        subjectCode: 'ENG-101',
        teacherName: 'Ms. Grace Lungu',
        test1Score: { raw: 26, max: 30, pct: 86.7 },
        test2Score: { raw: 25, max: 30, pct: 83.3 },
        test3Score: { raw: 27, max: 30, pct: 90 },
        assignmentAvgPct: 85,
        examScore: { raw: 82, max: 100, pct: 82 },
        totalContinuousAssessmentPct: 86.2,
        finalExamPct: 82,
        finalOverallPercentage: 84.5,
        eczGrade: '1',
        gradeLabel: 'Distinction',
        eczPoints: 1,
        teacherRemarks: 'Expressive vocabulary with strong grammatical clarity in written discourse.',
      },
      {
        subjectId: 'sub_sci',
        subjectName: 'Integrated Science',
        subjectCode: 'SCI-201',
        teacherName: 'Mr. Patrick Chanda',
        test1Score: { raw: 19, max: 20, pct: 95 },
        test2Score: { raw: 18, max: 20, pct: 90 },
        test3Score: { raw: 17, max: 20, pct: 85 },
        assignmentAvgPct: 92,
        examScore: { raw: 86, max: 100, pct: 86 },
        totalContinuousAssessmentPct: 90.5,
        finalExamPct: 86,
        finalOverallPercentage: 88.7,
        eczGrade: '1',
        gradeLabel: 'Distinction',
        eczPoints: 1,
        teacherRemarks: 'Excellent laboratory inquiry and understanding of scientific models.',
      },
      {
        subjectId: 'sub_cs',
        subjectName: 'Computer Studies',
        subjectCode: 'CMP-301',
        teacherName: 'Mr. Kelvin Tembo',
        test1Score: { raw: 20, max: 20, pct: 100 },
        test2Score: { raw: 19, max: 20, pct: 95 },
        test3Score: { raw: 19, max: 20, pct: 95 },
        assignmentAvgPct: 96,
        examScore: { raw: 92, max: 100, pct: 92 },
        totalContinuousAssessmentPct: 96.5,
        finalExamPct: 92,
        finalOverallPercentage: 94.7,
        eczGrade: '1',
        gradeLabel: 'Distinction',
        eczPoints: 1,
        teacherRemarks: 'Gifted aptitude in algorithm logic, typing, and digital problem solving.',
      },
      {
        subjectId: 'sub_civ',
        subjectName: 'Civic Education',
        subjectCode: 'CIV-203',
        teacherName: 'Ms. Grace Lungu',
        test1Score: { raw: 17, max: 20, pct: 85 },
        test2Score: { raw: 16, max: 20, pct: 80 },
        test3Score: { raw: 17, max: 20, pct: 85 },
        assignmentAvgPct: 80,
        examScore: { raw: 78, max: 100, pct: 78 },
        totalContinuousAssessmentPct: 82.5,
        finalExamPct: 78,
        finalOverallPercentage: 80.7,
        eczGrade: '1',
        gradeLabel: 'Distinction',
        eczPoints: 1,
        teacherRemarks: 'Deep appreciation of national constitutional tenets and governance.',
      },
      {
        subjectId: 'sub_geo',
        subjectName: 'Geography',
        subjectCode: 'GEO-202',
        teacherName: 'Ms. Grace Lungu',
        test1Score: { raw: 16, max: 20, pct: 80 },
        test2Score: { raw: 15, max: 20, pct: 75 },
        test3Score: { raw: 16, max: 20, pct: 80 },
        assignmentAvgPct: 78,
        examScore: { raw: 75, max: 100, pct: 75 },
        totalContinuousAssessmentPct: 78.2,
        finalExamPct: 75,
        finalOverallPercentage: 76.9,
        eczGrade: '1',
        gradeLabel: 'Distinction',
        eczPoints: 1,
        teacherRemarks: 'Solid map-reading acumen and physical topography analysis.',
      },
    ],
    totalMarksObtained: 523.6,
    totalMaxPossibleMarks: 600,
    averagePercentage: 87.3,
    aggregatePoints: 6, // 6 Distinctions = Aggregate 6 (Best Possible in ECZ standard)
    positionInClass: 2,
    totalStudentsInClass: 38,
    attendanceDaysPresent: 63,
    attendanceDaysAbsent: 2,
    totalSchoolDays: 65,
    attendancePercentage: 96.9,
    classTeacherRemarks: 'Mubita is a dependable, exceptionally focused student who exhibits exemplary leadership qualities in Grade 9A. He contributes purposefully in class and balances academic rigor with sports.',
    headTeacherRemarks: 'Outstanding aggregate result of Six (6) Points. Mubita exemplifies the highest standards of academic integrity and diligence at Kabwe National Technical High School. Strongly commended for Senior Secondary scholarship track.',
    conduct: 'Exemplary',
    nextTermBeginsDate: '2026-05-11',
    promotionStatus: 'Promoted to Next Grade',
    status: 'published',
    publishedDate: '2026-04-10',
    headTeacherSignatureName: 'Dr. Mwamba Banda (PhD, Ed.M)',
  },
  {
    id: 'rep_natasha_t1_2026',
    schoolId: 'school_kabwe_tech',
    schoolName: 'Kabwe National Technical High School',
    studentId: 'user_student_natasha',
    studentNumber: 'STU-2026-0015',
    studentName: 'Natasha Mulenga',
    gender: 'Female',
    grade: '9',
    classId: 'class_9a',
    className: 'Grade 9A',
    termId: 'term_1',
    termName: 'Term 1',
    academicYear: '2026',
    subjectResults: [
      {
        subjectId: 'sub_math',
        subjectName: 'Mathematics',
        subjectCode: 'MAT-401',
        teacherName: 'Mr. Kelvin Tembo',
        test1Score: { raw: 16, max: 20, pct: 80 },
        test2Score: { raw: 19, max: 20, pct: 95 },
        test3Score: { raw: 17, max: 20, pct: 85 },
        assignmentAvgPct: 90,
        examScore: { raw: 84, max: 100, pct: 84 },
        totalContinuousAssessmentPct: 87.5,
        finalExamPct: 84,
        finalOverallPercentage: 86.1,
        eczGrade: '1',
        gradeLabel: 'Distinction',
        eczPoints: 1,
        teacherRemarks: 'Outstanding analytical capability and meticulous problem-solving.',
      },
      {
        subjectId: 'sub_eng',
        subjectName: 'English Language',
        subjectCode: 'ENG-101',
        teacherName: 'Ms. Grace Lungu',
        test1Score: { raw: 28, max: 30, pct: 93.3 },
        test2Score: { raw: 28, max: 30, pct: 93.3 },
        test3Score: { raw: 29, max: 30, pct: 96.7 },
        assignmentAvgPct: 95,
        examScore: { raw: 90, max: 100, pct: 90 },
        totalContinuousAssessmentPct: 94.6,
        finalExamPct: 90,
        finalOverallPercentage: 92.8,
        eczGrade: '1',
        gradeLabel: 'Distinction',
        eczPoints: 1,
        teacherRemarks: 'Ranked top of the class in composition writing and literary analysis.',
      },
    ],
    totalMarksObtained: 178.9,
    totalMaxPossibleMarks: 200,
    averagePercentage: 89.4,
    aggregatePoints: 6,
    positionInClass: 1,
    totalStudentsInClass: 38,
    attendanceDaysPresent: 65,
    attendanceDaysAbsent: 0,
    totalSchoolDays: 65,
    attendancePercentage: 100,
    classTeacherRemarks: 'Natasha has maintained 100% attendance and secured position 1 in the class. A true role model.',
    headTeacherRemarks: 'An academic tour-de-force. Exemplary performance across all continuous assessments and final exams.',
    conduct: 'Exemplary',
    nextTermBeginsDate: '2026-05-11',
    promotionStatus: 'Promoted to Next Grade',
    status: 'published',
    publishedDate: '2026-04-10',
    headTeacherSignatureName: 'Dr. Mwamba Banda (PhD, Ed.M)',
  }
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'att_2026_04_08_9a',
    schoolId: 'school_kabwe_tech',
    classId: 'class_9a',
    className: 'Grade 9A',
    date: '2026-04-08',
    termId: 'term_1',
    academicYear: '2026',
    recordedByTeacherId: 'user_teacher_tembo',
    recordedByTeacherName: 'Mr. Kelvin Tembo',
    entries: [
      { studentId: 'user_student_mubita', studentNumber: 'STU-2026-0012', studentName: 'Mubita Mweemba', status: 'present' },
      { studentId: 'user_student_natasha', studentNumber: 'STU-2026-0015', studentName: 'Natasha Mulenga', status: 'present' },
      { studentId: 'user_student_chimwemwe', studentNumber: 'STU-2026-0021', studentName: 'Chimwemwe Zulu', status: 'present' },
    ],
  },
  {
    id: 'att_2026_04_09_9a',
    schoolId: 'school_kabwe_tech',
    classId: 'class_9a',
    className: 'Grade 9A',
    date: '2026-04-09',
    termId: 'term_1',
    academicYear: '2026',
    recordedByTeacherId: 'user_teacher_tembo',
    recordedByTeacherName: 'Mr. Kelvin Tembo',
    entries: [
      { studentId: 'user_student_mubita', studentNumber: 'STU-2026-0012', studentName: 'Mubita Mweemba', status: 'present' },
      { studentId: 'user_student_natasha', studentNumber: 'STU-2026-0015', studentName: 'Natasha Mulenga', status: 'present' },
      { studentId: 'user_student_chimwemwe', studentNumber: 'STU-2026-0021', studentName: 'Chimwemwe Zulu', status: 'late', reason: 'School bus mechanical delay' },
    ],
  },
];

export const INITIAL_ASSIGNMENTS: Assignment[] = [
  {
    id: 'asg_math_1',
    schoolId: 'school_kabwe_tech',
    classId: 'class_9a',
    className: 'Grade 9A',
    subjectId: 'sub_math',
    subjectName: 'Mathematics',
    teacherId: 'user_teacher_tembo',
    teacherName: 'Mr. Kelvin Tembo',
    title: 'Assignment 4: Simultaneous Linear Equations in 2 Variables',
    description: 'Solve the 10 practice problems from ECZ Past Examination Booklet 2024 (Pages 18-20). Show all working steps neatly.',
    maxScore: 20,
    dueDate: '2026-03-25',
    termId: 'term_1',
    createdAt: '2026-03-18',
    submissionsCount: 36,
    totalStudents: 38,
  },
  {
    id: 'asg_sci_1',
    schoolId: 'school_kabwe_tech',
    classId: 'class_9a',
    className: 'Grade 9A',
    subjectId: 'sub_sci',
    subjectName: 'Integrated Science',
    teacherId: 'user_teacher_chanda',
    teacherName: 'Mr. Patrick Chanda',
    title: 'Lab Practical Report: Electrolysis of Acidified Water',
    description: 'Submit your formal laboratory report detailing the cathode/anode gas ratio, equations, and safety precautions observed in Lab 2.',
    maxScore: 25,
    dueDate: '2026-03-28',
    termId: 'term_1',
    createdAt: '2026-03-20',
    submissionsCount: 37,
    totalStudents: 38,
  },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann_1',
    schoolId: 'school_kabwe_tech',
    title: 'Official Term 1 Digital Report Cards & PTA General Meeting',
    content: 'Dear Parents, Guardians, and Teachers: Term 1 official digital report cards have been consolidated and published via SchoolLink OS. The Annual General PTA Meeting will take place on Friday 10th April in the Main Assembly Hall starting at 09:00 AM CAT. Kindly review your child’s results and attendance summaries prior to the meeting.',
    category: 'PTA',
    authorName: 'Dr. Mwamba Banda',
    authorRole: 'head_teacher',
    targetRoles: ['parent', 'teacher', 'student', 'school_board'],
    isPinned: true,
    priority: 'urgent',
    createdAt: '2026-04-09T08:30:00Z',
  },
  {
    id: 'ann_2',
    schoolId: 'school_kabwe_tech',
    title: 'Term 2 Opening Date & Boarding Resumption Schedule',
    content: 'All learners and parents are notified that Term 2 commences strictly on Monday 11th May 2026. Boarding students are expected on campus between 08:00 AM and 16:00 PM on Sunday 10th May. Ensure full clearance of PTA project contributions.',
    category: 'Academic',
    authorName: 'Mrs. Chileshe Musonda',
    authorRole: 'deputy_head_teacher',
    targetRoles: ['parent', 'student', 'teacher'],
    isPinned: true,
    priority: 'normal',
    createdAt: '2026-04-08T14:15:00Z',
  },
  {
    id: 'ann_3',
    schoolId: 'school_kabwe_tech',
    title: 'Zambian National Science Fair & Robotics Competition 2026',
    content: 'Congratulations to our Grade 9 and Grade 11 STEM Innovation teams for qualifying for the National JETS (Junior Engineers, Technicians and Scientists) Fair in Lusaka next term!',
    category: 'General',
    authorName: 'Mr. Kelvin Tembo',
    authorRole: 'teacher',
    targetRoles: ['student', 'teacher', 'parent', 'school_board'],
    isPinned: false,
    priority: 'normal',
    createdAt: '2026-04-05T10:00:00Z',
  },
];

export const INITIAL_PTA_RECORDS: PTARecord[] = [
  {
    id: 'pta_kabwe_2026',
    schoolId: 'school_kabwe_tech',
    title: 'KTHS Parent-Teacher Association (PTA) Governance & Projects',
    meetingDate: '2026-04-10',
    venue: 'Main Auditorium & Live SchoolLink Stream',
    agendaItems: [
      'Adoption of Previous General Meeting Minutes',
      'Head Teacher’s Term 1 Academic Performance Overview',
      'Financial Report on Science Lab Solar Power Inverter Installation',
      'Approval of Modern High-Speed Fiber Internet Project for Senior Students',
      'Parent Q&A and Teacher Consultation Protocol',
    ],
    minutesSummary: 'The PTA Executive Committee commended the 94.2% overall pass rate in Grade 9 & 12 mock examinations. Phase 1 of the Science Laboratory Solar Power backup was commissioned at K185,000 ZMW. Next term focus will be classroom furniture refurbishment.',
    duesPerChildZMW: 450,
    totalFundsCollectedZMW: 342000,
    activeProjects: [
      { name: 'Science Labs 24/7 Solar Inverter & Battery Bank', budgetZMW: 185000, progressPercentage: 100, status: 'Completed' },
      { name: 'Computer Lab 50 Modern All-in-One Workstations', budgetZMW: 240000, progressPercentage: 75, status: 'In Progress' },
      { name: 'Borehole Water Purification & Tank Elevation System', budgetZMW: 95000, progressPercentage: 40, status: 'In Progress' },
    ],
  },
];

export const INITIAL_TIMETABLE: TimetableSlot[] = [
  { id: 'tt_1', dayOfWeek: 'Monday', periodNumber: 1, startTime: '07:30', endTime: '08:20', subjectName: 'Mathematics', teacherName: 'Mr. Kelvin Tembo', room: 'Block B - Room 4' },
  { id: 'tt_2', dayOfWeek: 'Monday', periodNumber: 2, startTime: '08:20', endTime: '09:10', subjectName: 'English Language', teacherName: 'Ms. Grace Lungu', room: 'Block B - Room 4' },
  { id: 'tt_3', dayOfWeek: 'Monday', periodNumber: 3, startTime: '09:30', endTime: '10:20', subjectName: 'Integrated Science', teacherName: 'Mr. Patrick Chanda', room: 'Science Lab 1' },
  { id: 'tt_4', dayOfWeek: 'Monday', periodNumber: 4, startTime: '10:20', endTime: '11:10', subjectName: 'Computer Studies', teacherName: 'Mr. Kelvin Tembo', room: 'Computer Lab' },
  { id: 'tt_5', dayOfWeek: 'Tuesday', periodNumber: 1, startTime: '07:30', endTime: '08:20', subjectName: 'Integrated Science', teacherName: 'Mr. Patrick Chanda', room: 'Science Lab 1' },
  { id: 'tt_6', dayOfWeek: 'Tuesday', periodNumber: 2, startTime: '08:20', endTime: '09:10', subjectName: 'Mathematics', teacherName: 'Mr. Kelvin Tembo', room: 'Block B - Room 4' },
  { id: 'tt_7', dayOfWeek: 'Tuesday', periodNumber: 3, startTime: '09:30', endTime: '10:20', subjectName: 'Civic Education', teacherName: 'Ms. Grace Lungu', room: 'Block B - Room 4' },
  { id: 'tt_8', dayOfWeek: 'Wednesday', periodNumber: 1, startTime: '07:30', endTime: '08:20', subjectName: 'English Language', teacherName: 'Ms. Grace Lungu', room: 'Block B - Room 4' },
  { id: 'tt_9', dayOfWeek: 'Wednesday', periodNumber: 2, startTime: '08:20', endTime: '09:10', subjectName: 'Geography', teacherName: 'Ms. Grace Lungu', room: 'Block B - Room 4' },
  { id: 'tt_10', dayOfWeek: 'Thursday', periodNumber: 1, startTime: '07:30', endTime: '08:20', subjectName: 'Mathematics', teacherName: 'Mr. Kelvin Tembo', room: 'Block B - Room 4' },
  { id: 'tt_11', dayOfWeek: 'Thursday', periodNumber: 2, startTime: '08:20', endTime: '09:10', subjectName: 'Icibemba', teacherName: 'Ms. Grace Lungu', room: 'Block B - Room 4' },
  { id: 'tt_12', dayOfWeek: 'Friday', periodNumber: 1, startTime: '07:30', endTime: '08:20', subjectName: 'Computer Studies', teacherName: 'Mr. Kelvin Tembo', room: 'Computer Lab' },
  { id: 'tt_13', dayOfWeek: 'Friday', periodNumber: 2, startTime: '08:20', endTime: '09:10', subjectName: 'Physical Education & Sports', teacherName: 'Mr. Patrick Chanda', room: 'Sports Grounds' },
];

export const INITIAL_ZOOM_MEETINGS: ZoomMeeting[] = [
  {
    id: 'zm_1',
    schoolId: 'school_kabwe_tech',
    topic: 'Grade 9A Mathematics: Quadratic Equations & Graph Sketching',
    subjectId: 'sub_mat',
    subjectName: 'Mathematics (ECZ 4024)',
    classId: 'cls_9a',
    className: 'Grade 9A',
    hostTeacherId: 'user_teacher_tembo',
    hostTeacherName: 'Mr. Kelvin Tembo',
    hostAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=160&auto=format&fit=crop&q=80',
    meetingId: '849 2039 1192',
    passcode: 'ECZ2026',
    startTime: '2026-08-27T08:00:00Z',
    durationMinutes: 50,
    status: 'live',
    joinUrl: 'https://zoom.us/j/84920391192?pwd=ECZ2026&uname=SchoolLinkLearner',
    lessonObjective: 'Master solving quadratic equations using factorisation and interpreting parabolic curve turning points for Paper 2.',
    curriculumCode: 'ECZ-MAT-SEC-09.4',
    attendeesCount: 28,
    isHostAudioMuted: false,
    isHostVideoOn: true,
  },
  {
    id: 'zm_2',
    schoolId: 'school_kabwe_tech',
    topic: 'Grade 11 Science: Electrolysis & Faraday’s Laws Practical Review',
    subjectId: 'sub_sci',
    subjectName: 'Physical Science (ECZ 5124)',
    classId: 'cls_11sci',
    className: 'Grade 11 Science',
    hostTeacherId: 'user_teacher_chanda',
    hostTeacherName: 'Mr. Patrick Chanda',
    hostAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=160&auto=format&fit=crop&q=80',
    meetingId: '912 4430 8710',
    passcode: 'SCIENCE99',
    startTime: '2026-08-27T10:30:00Z',
    durationMinutes: 60,
    status: 'upcoming',
    joinUrl: 'https://zoom.us/j/91244308710?pwd=SCIENCE99&uname=SchoolLinkLearner',
    lessonObjective: 'Quantitative calculations of mass deposited at electrodes and experimental setups review.',
    curriculumCode: 'ECZ-SCI-SEC-11.2',
    attendeesCount: 34,
  },
  {
    id: 'zm_3',
    schoolId: 'school_kabwe_tech',
    topic: 'Grade 9 English Language: Summary Writing & Comprehension Skills',
    subjectId: 'sub_eng',
    subjectName: 'English Language (ECZ 1121)',
    classId: 'cls_9a',
    className: 'Grade 9A',
    hostTeacherId: 'user_teacher_lungu',
    hostTeacherName: 'Ms. Grace Lungu',
    hostAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=160&auto=format&fit=crop&q=80',
    meetingId: '773 1940 3321',
    passcode: 'ENGLISH1',
    startTime: '2026-08-28T09:00:00Z',
    durationMinutes: 45,
    status: 'upcoming',
    joinUrl: 'https://zoom.us/j/77319403321?pwd=ENGLISH1&uname=SchoolLinkLearner',
    lessonObjective: 'Identifying 10 key summary points from passage without exceeding 120-word limit.',
    curriculumCode: 'ECZ-ENG-SEC-09.1',
    attendeesCount: 32,
  },
  {
    id: 'zm_4',
    schoolId: 'school_kabwe_tech',
    topic: 'Recorded: Computer Studies Programming Logic & Python Flowcharts',
    subjectId: 'sub_comp',
    subjectName: 'Computer Studies (ECZ 7010)',
    classId: 'cls_9a',
    className: 'Grade 9A',
    hostTeacherId: 'user_teacher_tembo',
    hostTeacherName: 'Mr. Kelvin Tembo',
    hostAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=160&auto=format&fit=crop&q=80',
    meetingId: '633 8812 0041',
    passcode: 'ARCHIVED',
    startTime: '2026-08-25T14:00:00Z',
    durationMinutes: 45,
    status: 'ended',
    joinUrl: 'https://zoom.us/rec/play/sample_kabwe_cs',
    recordingUrl: 'https://zoom.us/rec/play/sample_kabwe_cs',
    lessonObjective: 'Algorithmic pseudocode and flowchart conditional branching for Junior Secondary Exams.',
    curriculumCode: 'ECZ-COMP-SEC-09.3',
    attendeesCount: 30,
  },
];

export const INITIAL_DIRECT_MESSAGES: DirectMessage[] = [
  {
    id: 'msg_1',
    schoolId: 'school_kabwe_tech',
    senderId: 'user_teacher_tembo',
    senderName: 'Mr. Kelvin Tembo (Maths & CS Dept)',
    senderRole: 'teacher',
    senderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=160&auto=format&fit=crop&q=80',
    receiverId: 'usr_stu_1',
    receiverName: 'Mubita Mweemba',
    receiverRole: 'student',
    subject: 'Feedback on Quadratic Graph Homework (Ex 4.2)',
    content: 'Good morning Mubita. I reviewed your worksheet submission on turning point calculations. Your working on Question 4(b) was brilliant, but remember to label your x and y axes intercepts clearly as required in Section B of the ECZ Paper 2 examination.',
    timestamp: '2026-08-27T07:15:00Z',
    isRead: true,
    relatedSubject: 'Mathematics (ECZ 4024)',
    attachmentName: 'Quadratic_Graph_Corrections_Mubita.pdf',
    attachmentType: 'pdf',
  },
  {
    id: 'msg_2',
    schoolId: 'school_kabwe_tech',
    senderId: 'usr_stu_1',
    senderName: 'Mubita Mweemba',
    senderRole: 'student',
    senderAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=160&auto=format&fit=crop&q=80',
    receiverId: 'user_teacher_tembo',
    receiverName: 'Mr. Kelvin Tembo',
    receiverRole: 'teacher',
    subject: 'Clarification for Question 6 (Completing the Square)',
    content: 'Thank you Sir! I will make sure to label the coordinates. Could we quickly review the formula for finding the line of symmetry during today’s Zoom live session?',
    timestamp: '2026-08-27T07:42:00Z',
    isRead: false,
    relatedSubject: 'Mathematics (ECZ 4024)',
  },
  {
    id: 'msg_3',
    schoolId: 'school_kabwe_tech',
    senderId: 'user_teacher_lungu',
    senderName: 'Ms. Grace Lungu (Head of Languages)',
    senderRole: 'teacher',
    senderAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=160&auto=format&fit=crop&q=80',
    receiverId: 'usr_stu_1',
    receiverName: 'Mubita Mweemba',
    receiverRole: 'student',
    subject: 'National Debate Team Selection Practice',
    content: 'Dear Mubita, based on your essay writing and classroom presentation score (92%), you have been shortlisted to represent Kabwe Tech in the Inter-Provincial Schools Debate. Practice session will be held on Zoom on Friday afternoon at 15:00 hrs.',
    timestamp: '2026-08-26T15:30:00Z',
    isRead: true,
    relatedSubject: 'English Language',
    attachmentName: 'Debate_Motions_Central_Province_2026.pdf',
    attachmentType: 'pdf',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud_1',
    schoolId: 'school_kabwe_tech',
    userId: 'user_head_banda',
    userName: 'Dr. Mwamba Banda',
    userRole: 'head_teacher',
    action: 'APPROVAL_OF_TERM_ASSESSMENTS',
    details: 'Approved and published Term 1 Continuous Assessment Test results for Grade 9 Mathematics and Grade 11 Physics.',
    timestamp: '2026-08-27T06:00:00Z',
    ipAddress: '102.140.232.14',
  },
  {
    id: 'aud_2',
    schoolId: 'school_kabwe_tech',
    userId: 'user_teacher_tembo',
    userName: 'Mr. Kelvin Tembo',
    userRole: 'teacher',
    action: 'SCHEDULE_ZOOM_MEETING',
    details: 'Scheduled Zoom Virtual Classroom for Grade 9A Mathematics: Quadratic Function Curves & Turning Points.',
    timestamp: '2026-08-27T06:30:00Z',
    ipAddress: '102.140.232.19',
  },
  {
    id: 'aud_3',
    schoolId: 'school_kabwe_tech',
    userId: 'user_head_banda',
    userName: 'Dr. Mwamba Banda',
    userRole: 'head_teacher',
    action: 'SYSTEM_SYNC',
    details: 'Verified ECZ Examination Council standards compliance and MoE syllabus synchronization.',
    timestamp: '2026-08-27T07:00:00Z',
    ipAddress: '102.140.232.14',
  },
];

export const INITIAL_TEACHER_DUTY_LOGS: TeacherDailyDutyLog[] = [
  // MONDAY: 2026-08-24
  {
    id: 'duty_tembo_mon',
    teacherId: 'usr_tea_1',
    teacherName: 'Mr. Kelvin Tembo',
    teacherNumber: 'TS-2026-049',
    schoolId: 'school_kabwe_tech',
    date: '2026-08-24',
    checkInConfirmed: true,
    checkInTime: '07:10 AM',
    checkInTimestamp: '2026-08-24T07:10:00Z',
    checkOutConfirmed: true,
    checkOutTime: '16:15 PM',
    checkOutTimestamp: '2026-08-24T16:15:00Z',
    periods: [
      {
        id: 'mon_p1',
        periodNumber: 1,
        timeRange: '08:00 - 08:45',
        className: 'Grade 9A',
        subjectName: 'Mathematics',
        room: 'Room 12',
        topic: 'Introduction to Quadratic Relations & Parabolic Curves',
        status: 'taught',
        curriculumReference: 'ECZ-MATH-G9-SEC4',
      },
      {
        id: 'mon_p2',
        periodNumber: 2,
        timeRange: '08:45 - 09:30',
        className: 'Grade 9B',
        subjectName: 'Mathematics',
        room: 'Room 14',
        topic: 'Factorisation of Algebraic Expressions',
        status: 'taught',
        curriculumReference: 'ECZ-MATH-G9-SEC3',
      },
      {
        id: 'mon_p3',
        periodNumber: 3,
        timeRange: '09:45 - 10:30',
        className: 'Grade 11 Science',
        subjectName: 'Pure Mathematics',
        room: 'Lab B',
        topic: 'Limits and Continuity in Differential Calculus',
        status: 'taught',
        curriculumReference: 'ECZ-MATH-G11-CALC1',
      },
      {
        id: 'mon_p4',
        periodNumber: 4,
        timeRange: '10:30 - 11:15',
        className: 'Grade 10A',
        subjectName: 'Mathematics',
        room: 'Room 12',
        topic: 'Matrix Dimensions & Row-Column Multiplication',
        status: 'taught',
        curriculumReference: 'ECZ-MATH-G10-MAT1',
      },
      {
        id: 'mon_p5',
        periodNumber: 5,
        timeRange: '11:45 - 12:30',
        className: 'Grade 12 Tech',
        subjectName: 'Additional Mathematics',
        room: 'Comp Lab 1',
        topic: 'Inequalities in Linear Programming',
        status: 'not_taught',
        reasonIfNotTaught: 'School-wide Morning Briefing & Staff Assessment Committee',
        curriculumReference: 'ECZ-AD转变-G12-LP',
      },
      {
        id: 'mon_p6',
        periodNumber: 6,
        timeRange: '14:00 - 15:00',
        className: 'Grade 9 Remedial',
        subjectName: 'Mathematics Consultation',
        room: 'Room 12',
        topic: 'Algebraic Word Problems Review',
        status: 'taught',
        curriculumReference: 'ECZ-REMEDIAL-2026',
      }
    ],
    totalPeriodsTaught: 5,
    totalPeriodsScheduled: 6,
    dutyHandoverRemarks: 'Monday assembly completed; covered 5 of 6 scheduled periods.',
    sentToSchoolManager: true,
    sentToManagerTime: '16:15 PM',
    schoolManagerStatus: 'approved',
  },

  // TUESDAY: 2026-08-25
  {
    id: 'duty_tembo_tue',
    teacherId: 'usr_tea_1',
    teacherName: 'Mr. Kelvin Tembo',
    teacherNumber: 'TS-2026-049',
    schoolId: 'school_kabwe_tech',
    date: '2026-08-25',
    checkInConfirmed: true,
    checkInTime: '07:18 AM',
    checkInTimestamp: '2026-08-25T07:18:00Z',
    checkOutConfirmed: true,
    checkOutTime: '16:30 PM',
    checkOutTimestamp: '2026-08-25T16:30:00Z',
    periods: [
      {
        id: 'tue_p1',
        periodNumber: 1,
        timeRange: '08:00 - 08:45',
        className: 'Grade 9A',
        subjectName: 'Mathematics',
        room: 'Room 12',
        topic: 'Plotting Quadratic Graphs from Table of Values',
        status: 'taught',
        curriculumReference: 'ECZ-MATH-G9-SEC4',
      },
      {
        id: 'tue_p2',
        periodNumber: 2,
        timeRange: '08:45 - 09:30',
        className: 'Grade 9B',
        subjectName: 'Mathematics',
        room: 'Room 14',
        topic: 'Difference of Two Squares & Trinomials',
        status: 'taught',
        curriculumReference: 'ECZ-MATH-G9-SEC3',
      },
      {
        id: 'tue_p3',
        periodNumber: 3,
        timeRange: '09:45 - 10:30',
        className: 'Grade 11 Science',
        subjectName: 'Pure Mathematics',
        room: 'Lab B',
        topic: 'Power Rule of Differentiation (d/dx x^n)',
        status: 'taught',
        curriculumReference: 'ECZ-MATH-G11-CALC1',
      },
      {
        id: 'tue_p4',
        periodNumber: 4,
        timeRange: '10:30 - 11:15',
        className: 'Grade 10A',
        subjectName: 'Mathematics',
        room: 'Room 12',
        topic: 'Finding the Determinant of a 2x2 Matrix',
        status: 'taught',
        curriculumReference: 'ECZ-MATH-G10-MAT1',
      },
      {
        id: 'tue_p5',
        periodNumber: 5,
        timeRange: '11:45 - 12:30',
        className: 'Grade 12 Tech',
        subjectName: 'Additional Mathematics',
        room: 'Comp Lab 1',
        topic: 'Feasible Regions and Shading Unwanted Regions',
        status: 'taught',
        curriculumReference: 'ECZ-AD转变-G12-LP',
      },
      {
        id: 'tue_p6',
        periodNumber: 6,
        timeRange: '14:00 - 15:00',
        className: 'Grade 9 Remedial',
        subjectName: 'Mathematics Consultation',
        room: 'Zoom Virtual Room 102',
        topic: 'Live Screen Graph Plotting Demonstration',
        status: 'taught',
        curriculumReference: 'ECZ-REMEDIAL-2026',
      }
    ],
    totalPeriodsTaught: 6,
    totalPeriodsScheduled: 6,
    dutyHandoverRemarks: '100% syllabus target achieved today. All 6 periods taught without interruptions.',
    sentToSchoolManager: true,
    sentToManagerTime: '16:30 PM',
    schoolManagerStatus: 'approved',
  },

  // WEDNESDAY: 2026-08-26
  {
    id: 'duty_tembo_wed',
    teacherId: 'usr_tea_1',
    teacherName: 'Mr. Kelvin Tembo',
    teacherNumber: 'TS-2026-049',
    schoolId: 'school_kabwe_tech',
    date: '2026-08-26',
    checkInConfirmed: true,
    checkInTime: '07:15 AM',
    checkInTimestamp: '2026-08-26T07:15:00Z',
    checkOutConfirmed: true,
    checkOutTime: '16:20 PM',
    checkOutTimestamp: '2026-08-26T16:20:00Z',
    periods: [
      {
        id: 'wed_p1',
        periodNumber: 1,
        timeRange: '08:00 - 08:45',
        className: 'Grade 9A',
        subjectName: 'Mathematics',
        room: 'Room 12',
        topic: 'Identifying Roots and Y-Intercept from Quadratic Curves',
        status: 'taught',
        curriculumReference: 'ECZ-MATH-G9-SEC4',
      },
      {
        id: 'wed_p2',
        periodNumber: 2,
        timeRange: '08:45 - 09:30',
        className: 'Grade 9B',
        subjectName: 'Mathematics',
        room: 'Room 14',
        topic: 'Grouping Terms for Factoring',
        status: 'taught',
        curriculumReference: 'ECZ-MATH-G9-SEC3',
      },
      {
        id: 'wed_p3',
        periodNumber: 3,
        timeRange: '09:45 - 10:30',
        className: 'Grade 11 Science',
        subjectName: 'Pure Mathematics',
        room: 'Lab B',
        topic: 'Gradients of Curves and Tangents',
        status: 'not_taught',
        reasonIfNotTaught: 'National Science Fair Provincial Coordination Meeting',
        curriculumReference: 'ECZ-MATH-G11-CALC1',
      },
      {
        id: 'wed_p4',
        periodNumber: 4,
        timeRange: '10:30 - 11:15',
        className: 'Grade 10A',
        subjectName: 'Mathematics',
        room: 'Room 12',
        topic: 'Matrix Inversion Method',
        status: 'taught',
        curriculumReference: 'ECZ-MATH-G10-MAT1',
      },
      {
        id: 'wed_p5',
        periodNumber: 5,
        timeRange: '11:45 - 12:30',
        className: 'Grade 12 Tech',
        subjectName: 'Additional Mathematics',
        room: 'Comp Lab 1',
        topic: 'Optimisation & Maximum Profit Calculations',
        status: 'taught',
        curriculumReference: 'ECZ-AD转变-G12-LP',
      },
      {
        id: 'wed_p6',
        periodNumber: 6,
        timeRange: '14:00 - 15:00',
        className: 'Grade 9 Remedial',
        subjectName: 'Mathematics Consultation',
        room: 'Room 12',
        topic: 'Weekly Quiz Diagnostic Feedback',
        status: 'taught',
        curriculumReference: 'ECZ-REMEDIAL-2026',
      }
    ],
    totalPeriodsTaught: 5,
    totalPeriodsScheduled: 6,
    dutyHandoverRemarks: 'Missed Period 3 due to Science Fair committee; remedial time allocated for Grade 11 Science.',
    sentToSchoolManager: true,
    sentToManagerTime: '16:20 PM',
    schoolManagerStatus: 'approved',
  },

  // THURSDAY (TODAY): 2026-08-27
  {
    id: 'duty_tembo_today',
    teacherId: 'usr_tea_1',
    teacherName: 'Mr. Kelvin Tembo',
    teacherNumber: 'TS-2026-049',
    schoolId: 'school_kabwe_tech',
    date: '2026-08-27',
    checkInConfirmed: true,
    checkInTime: '07:14 AM',
    checkInTimestamp: '2026-08-27T07:14:22Z',
    checkOutConfirmed: false,
    checkOutTime: null,
    checkOutTimestamp: null,
    periods: [
      {
        id: 'p_1',
        periodNumber: 1,
        timeRange: '08:00 - 08:45',
        className: 'Grade 9A',
        subjectName: 'Mathematics',
        room: 'Room 12 (North Wing)',
        topic: 'Quadratic Curves & Turning Point Coordinates',
        status: 'taught',
        curriculumReference: 'ECZ-MATH-G9-SEC4',
      },
      {
        id: 'p_2',
        periodNumber: 2,
        timeRange: '08:45 - 09:30',
        className: 'Grade 9B',
        subjectName: 'Mathematics',
        room: 'Room 14 (Science Block)',
        topic: 'Factorisation of Trinomials & Common Factors',
        status: 'taught',
        curriculumReference: 'ECZ-MATH-G9-SEC3',
      },
      {
        id: 'p_3',
        periodNumber: 3,
        timeRange: '09:45 - 10:30',
        className: 'Grade 11 Science',
        subjectName: 'Pure Mathematics',
        room: 'Lab B',
        topic: 'Calculus: Differentiation from First Principles',
        status: 'taught',
        curriculumReference: 'ECZ-MATH-G11-CALC1',
      },
      {
        id: 'p_4',
        periodNumber: 4,
        timeRange: '10:30 - 11:15',
        className: 'Grade 10A',
        subjectName: 'Mathematics',
        room: 'Room 12',
        topic: 'Matrices: Determinant and Inverse of 2x2 Matrix',
        status: 'not_taught',
        reasonIfNotTaught: 'Relief duty covering mid-term laboratory setup',
        curriculumReference: 'ECZ-MATH-G10-MAT1',
      },
      {
        id: 'p_5',
        periodNumber: 5,
        timeRange: '11:45 - 12:30',
        className: 'Grade 12 Tech',
        subjectName: 'Additional Mathematics',
        room: 'Comp Lab 1',
        topic: 'Linear Programming & Feasible Regions (ECZ Paper 2)',
        status: 'taught',
        curriculumReference: 'ECZ-AD转变-G12-LP',
      },
      {
        id: 'p_6',
        periodNumber: 6,
        timeRange: '14:00 - 15:00',
        className: 'Grade 9 Remedial',
        subjectName: 'Mathematics Consultation',
        room: 'Zoom Virtual Room 102',
        topic: 'Interactive Problem Solving & Homework Clarifications',
        status: 'taught',
        curriculumReference: 'ECZ-REMEDIAL-2026',
      }
    ],
    totalPeriodsTaught: 5,
    totalPeriodsScheduled: 6,
    dutyHandoverRemarks: 'Covered Paper 2 quadratic graphs with Grade 9A; set up Zoom practice review for afternoon session.',
    sentToSchoolManager: false,
    sentToManagerTime: null,
    schoolManagerStatus: 'submitted',
  },

  // FRIDAY: 2026-08-28
  {
    id: 'duty_tembo_fri',
    teacherId: 'usr_tea_1',
    teacherName: 'Mr. Kelvin Tembo',
    teacherNumber: 'TS-2026-049',
    schoolId: 'school_kabwe_tech',
    date: '2026-08-28',
    checkInConfirmed: true,
    checkInTime: '07:12 AM',
    checkInTimestamp: '2026-08-28T07:12:00Z',
    checkOutConfirmed: true,
    checkOutTime: '15:45 PM',
    checkOutTimestamp: '2026-08-28T15:45:00Z',
    periods: [
      {
        id: 'fri_p1',
        periodNumber: 1,
        timeRange: '08:00 - 08:45',
        className: 'Grade 9A',
        subjectName: 'Mathematics',
        room: 'Room 12',
        topic: 'Weekly Revision & Timed Past Paper Drill',
        status: 'taught',
        curriculumReference: 'ECZ-MATH-G9-SEC4',
      },
      {
        id: 'fri_p2',
        periodNumber: 2,
        timeRange: '08:45 - 09:30',
        className: 'Grade 9B',
        subjectName: 'Mathematics',
        room: 'Room 14',
        topic: 'Consolidation of Factorisation Questions',
        status: 'taught',
        curriculumReference: 'ECZ-MATH-G9-SEC3',
      },
      {
        id: 'fri_p3',
        periodNumber: 3,
        timeRange: '09:45 - 10:30',
        className: 'Grade 11 Science',
        subjectName: 'Pure Mathematics',
        room: 'Lab B',
        topic: 'Applications of Derivatives: Velocity & Acceleration',
        status: 'taught',
        curriculumReference: 'ECZ-MATH-G11-CALC1',
      },
      {
        id: 'fri_p4',
        periodNumber: 4,
        timeRange: '10:30 - 11:15',
        className: 'Grade 10A',
        subjectName: 'Mathematics',
        room: 'Room 12',
        topic: 'Solving Simultaneous Equations using Matrices',
        status: 'taught',
        curriculumReference: 'ECZ-MATH-G10-MAT1',
      },
      {
        id: 'fri_p5',
        periodNumber: 5,
        timeRange: '11:45 - 12:30',
        className: 'Grade 12 Tech',
        subjectName: 'Additional Mathematics',
        room: 'Comp Lab 1',
        topic: 'Past Exam Paper 2 Section B In-Depth Walkthrough',
        status: 'taught',
        curriculumReference: 'ECZ-AD转变-G12-LP',
      }
    ],
    totalPeriodsTaught: 5,
    totalPeriodsScheduled: 5,
    dutyHandoverRemarks: 'Friday classes concluded smoothly. End-of-week registers closed and verified.',
    sentToSchoolManager: true,
    sentToManagerTime: '15:45 PM',
    schoolManagerStatus: 'approved',
  },

  // MRS CHILESHE MWANZA (SCIENCE)
  {
    id: 'duty_chileshe_today',
    teacherId: 'usr_tea_2',
    teacherName: 'Mrs. Chileshe Mwanza',
    teacherNumber: 'TS-2026-081',
    schoolId: 'school_kabwe_tech',
    date: '2026-08-27',
    checkInConfirmed: true,
    checkInTime: '07:22 AM',
    checkInTimestamp: '2026-08-27T07:22:00Z',
    checkOutConfirmed: true,
    checkOutTime: '16:05 PM',
    checkOutTimestamp: '2026-08-27T16:05:00Z',
    periods: [
      {
        id: 'cp_1',
        periodNumber: 1,
        timeRange: '08:00 - 08:45',
        className: 'Grade 11 Science',
        subjectName: 'Physics',
        room: 'Physics Lab 1',
        topic: 'Ohm\'s Law & Resistance in Series/Parallel',
        status: 'taught',
      },
      {
        id: 'cp_2',
        periodNumber: 2,
        timeRange: '08:45 - 09:30',
        className: 'Grade 12 Science',
        subjectName: 'Chemistry',
        room: 'Chemistry Lab',
        topic: 'Electrolysis of Molten Lead(II) Bromide',
        status: 'taught',
      },
      {
        id: 'cp_3',
        periodNumber: 3,
        timeRange: '10:30 - 11:15',
        className: 'Grade 10B',
        subjectName: 'Integrated Science',
        room: 'Room 8',
        topic: 'Human Circulatory System & Heart Chambers',
        status: 'taught',
      },
      {
        id: 'cp_4',
        periodNumber: 4,
        timeRange: '11:45 - 12:30',
        className: 'Grade 9B',
        subjectName: 'Integrated Science',
        room: 'Room 9',
        topic: 'Acids, Bases & Universal Indicators',
        status: 'taught',
      }
    ],
    totalPeriodsTaught: 4,
    totalPeriodsScheduled: 4,
    dutyHandoverRemarks: 'All science practicals completed safely with zero reagent spills.',
    sentToSchoolManager: true,
    sentToManagerTime: '16:05 PM',
    schoolManagerStatus: 'reviewed',
  }
];

// Initial Facebook-Style Campus Stories
export const INITIAL_STORIES: StoryItem[] = [
  {
    id: 'story_head_1',
    schoolId: 'school_kabwe_tech',
    userId: 'user_head_mwape',
    userName: 'Dr. John Mwape',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    userRole: 'head_teacher',
    mediaType: 'text',
    content: '🎓 Welcome back to Term 1 2026! Let us commit to 100% academic excellence and character building across all grades.',
    backgroundGradient: 'from-blue-600 via-indigo-700 to-purple-800',
    caption: 'Official Welcome from the Head Teacher',
    timestamp: '2026-01-15T08:00:00Z',
    expiresAt: '2026-01-16T08:00:00Z',
    likes: ['user_teacher_tembo', 'user_parent_mweemba'],
    reactions: [
      { userId: 'user_teacher_tembo', emoji: '👏', userName: 'Mr. Kelvin Tembo' },
      { userId: 'user_parent_mweemba', emoji: '❤️', userName: 'Mr. Joseph Mweemba' }
    ],
    viewedByUserIds: ['user_student_mubita', 'user_teacher_tembo']
  },
  {
    id: 'story_finance_tembo',
    schoolId: 'school_kabwe_tech',
    userId: 'user_teacher_tembo',
    userName: 'Mr. Kelvin Tembo',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    userRole: 'teacher',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800&auto=format&fit=crop&q=80',
    caption: '📐 Senior Math Olympiad prep session in Lab 2 today at 15:30. Bring your scientific calculators!',
    timestamp: '2026-01-15T09:30:00Z',
    expiresAt: '2026-01-16T09:30:00Z',
    likes: ['user_student_mubita', 'user_student_natasha'],
    reactions: [
      { userId: 'user_student_mubita', emoji: '🔥', userName: 'Mubita Mweemba' },
      { userId: 'user_student_natasha', emoji: '💡', userName: 'Natasha Mulenga' }
    ],
    viewedByUserIds: ['user_student_mubita']
  },
  {
    id: 'story_parent_mweemba',
    schoolId: 'school_kabwe_tech',
    userId: 'user_parent_mweemba',
    userName: 'Mr. Joseph Mweemba',
    userAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80',
    userRole: 'parent',
    mediaType: 'text',
    content: '🤝 Proud to see the new solar power project being launched by our PTA committee. Great progress for our children!',
    backgroundGradient: 'from-emerald-600 via-teal-700 to-cyan-800',
    caption: 'PTA Committee Update',
    timestamp: '2026-01-15T11:00:00Z',
    expiresAt: '2026-01-16T11:00:00Z',
    likes: ['user_head_mwape', 'user_deputy_musonda'],
    reactions: [
      { userId: 'user_head_mwape', emoji: '👏', userName: 'Dr. John Mwape' }
    ],
    viewedByUserIds: []
  },
  {
    id: 'story_student_mubita',
    schoolId: 'school_kabwe_tech',
    userId: 'user_student_mubita',
    userName: 'Mubita Mweemba',
    userAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=120&auto=format&fit=crop&q=80',
    userRole: 'student',
    mediaType: 'text',
    content: '📚 Mastered Quadratic equations and Parabolic motion using the new Smart Study Notes tool! 100% on the diagnostic quiz!',
    backgroundGradient: 'from-amber-600 via-orange-600 to-red-600',
    caption: 'Study Sprint complete',
    timestamp: '2026-01-15T14:15:00Z',
    expiresAt: '2026-01-16T14:15:00Z',
    likes: ['user_teacher_tembo'],
    reactions: [
      { userId: 'user_teacher_tembo', emoji: '🎓', userName: 'Mr. Kelvin Tembo' }
    ],
    viewedByUserIds: []
  }
];

// Initial Group Classes, Grade Groups, PTA & Clubs
export const INITIAL_GROUPS: SchoolGroup[] = [
  {
    id: 'grp_pta_assembly',
    schoolId: 'school_kabwe_tech',
    name: 'PTA General Assembly & Executive Council',
    category: 'pta_group',
    grade: 'All',
    description: 'Official Parent-Teacher Association hub. All parents, teachers, administration, and board members are automatically joined to coordinate school development and student welfare.',
    bannerGradient: 'from-emerald-700 via-teal-800 to-slate-900',
    icon: '🤝',
    createdById: 'user_head_mwape',
    createdByName: 'Dr. John Mwape',
    isAutoJoinedPta: true, // Everyone except students
    memberIds: [
      'user_head_mwape',
      'user_deputy_musonda',
      'user_teacher_tembo',
      'user_teacher_lungu',
      'user_teacher_chanda',
      'user_teacher_phiri',
      'user_parent_mweemba',
      'user_parent_mulenga',
      'user_board_chilufya'
    ],
    postsCount: 14,
    recentActivity: '2 hours ago',
    createdAt: '2026-01-05T10:00:00Z'
  },
  {
    id: 'grp_grade_9',
    schoolId: 'school_kabwe_tech',
    name: 'Grade 9 National Academic Cohort (All Streams)',
    category: 'grade_group',
    grade: '9',
    description: 'Central academic community for all Grade 9 students, teachers, and subject coordinators preparing for junior secondary examinations.',
    bannerGradient: 'from-indigo-700 via-purple-800 to-slate-900',
    icon: '🎓',
    createdById: 'user_deputy_musonda',
    createdByName: 'Mrs. Chileshe Musonda',
    memberIds: [
      'user_deputy_musonda',
      'user_teacher_tembo',
      'user_teacher_lungu',
      'user_teacher_chanda',
      'user_student_mubita',
      'user_student_natasha',
      'user_student_chimwemwe'
    ],
    postsCount: 22,
    recentActivity: '30 mins ago',
    createdAt: '2026-01-06T09:00:00Z'
  },
  {
    id: 'grp_class_9a',
    schoolId: 'school_kabwe_tech',
    name: 'Grade 9A Official Class Group',
    category: 'class_group',
    grade: '9',
    classId: 'class_9a',
    description: 'Daily homework, announcements, timetable reminders, and peer discussions for Grade 9A homeroom students and class teachers.',
    bannerGradient: 'from-blue-700 via-sky-800 to-slate-900',
    icon: '🏫',
    createdById: 'user_teacher_tembo',
    createdByName: 'Mr. Kelvin Tembo',
    memberIds: [
      'user_teacher_tembo',
      'user_teacher_lungu',
      'user_student_mubita',
      'user_student_natasha',
      'user_student_chimwemwe'
    ],
    postsCount: 38,
    recentActivity: '10 mins ago',
    createdAt: '2026-01-08T08:30:00Z'
  },
  {
    id: 'grp_grade_11',
    schoolId: 'school_kabwe_tech',
    name: 'Grade 11 Senior Secondary League',
    category: 'grade_group',
    grade: '11',
    description: 'Senior secondary collaborative space covering Pure Sciences, Technical drawing, and Commercial syllabi.',
    bannerGradient: 'from-amber-700 via-orange-800 to-slate-900',
    icon: '🔬',
    createdById: 'user_teacher_chanda',
    createdByName: 'Mr. Patrick Chanda',
    memberIds: [
      'user_teacher_chanda',
      'user_teacher_phiri',
      'user_student_dalitso'
    ],
    postsCount: 19,
    recentActivity: '1 day ago',
    createdAt: '2026-01-08T11:00:00Z'
  },
  {
    id: 'grp_jets_science',
    schoolId: 'school_kabwe_tech',
    name: 'JETS (Junior Engineers, Technicians & Scientists) Club',
    category: 'club',
    grade: 'All',
    description: 'Innovation society building national STEM projects, robotics prototypes, and solar tech inventions.',
    bannerGradient: 'from-cyan-700 via-blue-800 to-indigo-950',
    icon: '🚀',
    createdById: 'user_teacher_chanda',
    createdByName: 'Mr. Patrick Chanda',
    memberIds: [
      'user_teacher_chanda',
      'user_teacher_tembo',
      'user_student_mubita',
      'user_student_dalitso',
      'user_student_natasha'
    ],
    postsCount: 16,
    recentActivity: '3 hours ago',
    createdAt: '2026-01-10T14:00:00Z'
  }
];

// Initial Group Posts
export const INITIAL_GROUP_POSTS: GroupPost[] = [
  {
    id: 'post_pta_1',
    groupId: 'grp_pta_assembly',
    schoolId: 'school_kabwe_tech',
    authorId: 'user_parent_mweemba',
    authorName: 'Mr. Joseph Mweemba',
    authorAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80',
    authorRole: 'parent',
    content: 'Dear PTA Members and Teachers, the procurement of the 45kVA backup solar inverter system has been successfully verified. We expect installation to complete before the mid-term examinations.',
    likes: ['user_head_mwape', 'user_teacher_tembo', 'user_teacher_phiri'],
    comments: [
      {
        id: 'comm_1',
        authorId: 'user_head_mwape',
        authorName: 'Dr. John Mwape (Head Teacher)',
        authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
        authorRole: 'head_teacher',
        content: 'Excellent progress Mr. Mweemba. This ensures uninterrupted computer lab practicals and evening prep.',
        timestamp: '2026-01-14T14:30:00Z'
      }
    ],
    createdAt: '2026-01-14T13:00:00Z',
    isPinned: true
  },
  {
    id: 'post_gr9_1',
    groupId: 'grp_grade_9',
    schoolId: 'school_kabwe_tech',
    authorId: 'user_teacher_tembo',
    authorName: 'Mr. Kelvin Tembo',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    authorRole: 'teacher',
    content: '📢 Grade 9 Mathematics Revision: Please review the Quadratic Equations Masterclass notes in the Smart Study Notes tab. Pay special attention to the completing-the-square derivation for Paper 2.',
    likes: ['user_student_mubita', 'user_student_natasha', 'user_student_chimwemwe'],
    comments: [
      {
        id: 'comm_2',
        authorId: 'user_student_mubita',
        authorName: 'Mubita Mweemba',
        authorAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=120&auto=format&fit=crop&q=80',
        authorRole: 'student',
        content: 'Thank you Sir! The step-by-step proofs made the formula much easier to understand.',
        timestamp: '2026-01-15T10:15:00Z'
      }
    ],
    createdAt: '2026-01-15T09:00:00Z',
    isPinned: true
  },
  {
    id: 'post_class9a_1',
    groupId: 'grp_class_9a',
    schoolId: 'school_kabwe_tech',
    authorId: 'user_teacher_lungu',
    authorName: 'Ms. Grace Lungu',
    authorAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80',
    authorRole: 'teacher',
    content: 'Reminder for Grade 9A: English debate preparations on "Technological Innovation vs Agriculture in Zambia" will take place this Thursday during period 4.',
    likes: ['user_student_mubita', 'user_student_chimwemwe'],
    comments: [],
    createdAt: '2026-01-15T11:20:00Z'
  }
];

// Initial Finance Team Publications (Confidential to Parents + Head + Deputy vs Public Broadcasts)
export const INITIAL_FINANCE_PUBLICATIONS: FinancePublication[] = [
  {
    id: 'fin_pub_term1_fees',
    schoolId: 'school_kabwe_tech',
    title: 'Term 1 2026 Approved Tuition & Boarding Fee Schedule',
    content: 'Official approved fee schedule for Term 1. All payments must be deposited directly to the school bank account or via verified Airtel/MTN School Pay merchant codes. Please attach deposit slips in the Parent Portal.',
    category: 'fee_schedule',
    targetAudience: 'finance_restricted', // RESTRICTED: Parents, Head Teacher, Deputy Head Teacher ONLY
    amountZMW: 3200,
    dueDate: '2026-02-15',
    bankDetails: {
      bankName: 'Zambia National Commercial Bank (Zanaco)',
      accountName: 'Kabwe National Technical High School - Operations',
      accountNumber: '1049-8839-2041',
      branch: 'Kabwe Main Branch',
      mobileMoneyCode: '*115*4*1049# (Airtel) / *303*2*1049# (MTN)'
    },
    authorId: 'user_teacher_tembo',
    authorName: 'Mr. Kelvin Tembo',
    authorRole: 'teacher',
    isFinanceTeamAuthor: true,
    financeRoleTitle: 'Senior Finance Committee Officer & Accounts Liaison',
    createdAt: '2026-01-10T08:00:00Z',
    isPinned: true,
    attachments: [
      { name: 'Term_1_2026_Fee_Structure_Official.pdf', size: '240 KB', type: 'application/pdf' }
    ],
    viewCount: 68
  },
  {
    id: 'fin_pub_pta_levy',
    schoolId: 'school_kabwe_tech',
    title: 'PTA Development Levy: Solar Power Infrastructure & Lab Upgrade',
    content: 'The PTA Executive Committee has set the Term 1 Development Levy at K450 per student to finance the completion of the 45kVA Solar Inverter installation and high-speed fiber internet for the Computer Lab.',
    category: 'pta_levy_notice',
    targetAudience: 'finance_restricted', // RESTRICTED: Parents, Head Teacher, Deputy Head Teacher ONLY
    amountZMW: 450,
    dueDate: '2026-02-28',
    bankDetails: {
      bankName: 'Indo Zambia Bank',
      accountName: 'Kabwe Tech High School PTA Project Fund',
      accountNumber: '0420-1199-3011',
      branch: 'Kabwe Town',
      mobileMoneyCode: 'PTA-KTH-450'
    },
    authorId: 'user_teacher_phiri',
    authorName: 'Mrs. Bwalya Phiri',
    authorRole: 'teacher',
    isFinanceTeamAuthor: true,
    financeRoleTitle: 'Bursary Liaison & Audit Secretary',
    createdAt: '2026-01-12T10:30:00Z',
    isPinned: true,
    attachments: [
      { name: 'PTA_Solar_Project_Budget_Breakdown.pdf', size: '410 KB', type: 'application/pdf' }
    ],
    viewCount: 52
  },
  {
    id: 'fin_pub_bursary_guide',
    schoolId: 'school_kabwe_tech',
    title: 'National CDF Secondary School Bursary Application Guidance',
    content: 'Step-by-step guidance for vulnerable students and parents applying for the Constituency Development Fund (CDF) secondary school bursary allocation for the 2026 academic year.',
    category: 'budget_report',
    targetAudience: 'all_roles', // PUBLIC: Broadcast to EVERY ROLE (Students, Teachers, Parents, Board)
    authorId: 'user_teacher_tembo',
    authorName: 'Mr. Kelvin Tembo',
    authorRole: 'teacher',
    isFinanceTeamAuthor: true,
    financeRoleTitle: 'Senior Finance Committee Officer',
    createdAt: '2026-01-14T09:00:00Z',
    isPinned: false,
    attachments: [
      { name: 'CDF_Secondary_Bursary_Form_2026.pdf', size: '1.2 MB', type: 'application/pdf' }
    ],
    viewCount: 142
  }
];

// -------------------------------------------------------------
// INITIAL PARENT DATA (FEES, PAYMENTS, BUSES, DISCIPLINE, ETC.)
// -------------------------------------------------------------

import {
  ParentFeeStatement,
  ParentPaymentTransaction,
  BusRouteTracker,
  GuardianPickupPass,
  StudentBehaviorLog,
  ParentTeacherConference,
  PermissionSlip,
  HealthClinicVisit,
  CanteenWallet
} from './types';

export const INITIAL_PARENT_FEE_STATEMENTS: Record<string, ParentFeeStatement> = {
  'STU-2026-0012': {
    studentNumber: 'STU-2026-0012',
    studentName: 'Chileshe Mwila',
    className: 'Grade 9A',
    academicYear: '2026',
    termId: 'term_1',
    totalInvoiced: 2850,
    totalPaid: 2150,
    balanceDue: 700,
    dueDate: '2026-02-28',
    items: [
      { id: 'item_tuition', name: 'Term 1 Government Subsidized Tuition', amount: 1200, isMandatory: true, category: 'tuition' },
      { id: 'item_pta', name: 'PTA Development Levy (Solar Project)', amount: 450, isMandatory: true, category: 'pta' },
      { id: 'item_sci_lab', name: 'Science Laboratory & Chemical Consumables', amount: 350, isMandatory: true, category: 'lab' },
      { id: 'item_ict_lab', name: 'Computer Studies & Internet Access Fee', amount: 350, isMandatory: true, category: 'lab' },
      { id: 'item_ecz_prep', name: 'Continuous Assessment & Mock Exam Assessment Fee', amount: 250, isMandatory: true, category: 'tuition' },
      { id: 'item_sports', name: 'Inter-School Sports & Cultural Levy', amount: 250, isMandatory: true, category: 'uniform_books' },
    ],
    transactions: [
      {
        id: 'tx_pay_001',
        receiptNumber: 'KT-REC-2026-0419',
        studentNumber: 'STU-2026-0012',
        studentName: 'Chileshe Mwila',
        parentId: 'user_parent_mwila',
        parentName: 'Mrs. Gertrude Mwila',
        amount: 1450,
        termId: 'term_1',
        academicYear: '2026',
        channel: 'airtel_money',
        referenceNumber: 'AT-992014022',
        timestamp: '2026-01-15T10:24:00Z',
        status: 'completed',
        feeItemName: 'Term 1 Tuition Deposit & PTA Levy',
        notes: 'Paid via Airtel Money Paybill'
      },
      {
        id: 'tx_pay_002',
        receiptNumber: 'KT-REC-2026-0832',
        studentNumber: 'STU-2026-0012',
        studentName: 'Chileshe Mwila',
        parentId: 'user_parent_mwila',
        parentName: 'Mrs. Gertrude Mwila',
        amount: 700,
        termId: 'term_1',
        academicYear: '2026',
        channel: 'zanaco_schoolpay',
        referenceNumber: 'ZN-SCH-774021',
        timestamp: '2026-02-04T14:15:00Z',
        status: 'completed',
        feeItemName: 'Science Lab & ICT Practical Fees',
        notes: 'Zanaco SchoolPay Direct Deposit'
      }
    ]
  }
};

export const INITIAL_BUS_TRACKERS: BusRouteTracker[] = [
  {
    id: 'bus_route_04',
    routeNumber: 'Route 4B',
    busRegistrationNumber: 'BAH 8821 ZM',
    busNumber: 'Kabwe Tech Bus 04 (Toyota Coaster 32-Seater)',
    driverName: 'Mr. Joseph Sakala',
    driverPhone: '+260 977 441029',
    matronName: 'Mrs. Patricia Tembo',
    matronPhone: '+260 966 882033',
    supervisorName: 'Mrs. Patricia Tembo (Bus Matron)',
    supervisorPhone: '+260 966 882033',
    routeTitle: 'Kabwe Town Centre - Mukobeko - Highridge Corridor',
    currentLocation: 'Approaching Highridge Roundabout (Near Civic Centre)',
    currentLocationName: 'Approaching Highridge Roundabout (Near Civic Centre)',
    tripType: 'morning_pickup',
    status: 'morning_in_transit',
    etaMinutes: 12,
    assignedStudents: ['STU-2026-0012', 'STU-2026-0034', 'STU-2026-0056'],
    assignedStudentNumbers: ['STU-2026-0012', 'STU-2026-0034', 'STU-2026-0056'],
    estimatedArrivalAtSchool: '07:35 AM',
    lastUpdated: 'Just now (GPS Synced)',
    stops: [
      { id: 'stop_1', name: 'Mukobeko Main Gate Turnoff', stopName: 'Mukobeko Main Gate Turnoff', scheduledTime: '06:45 AM', scheduledMorningTime: '06:45 AM', scheduledAfternoonTime: '15:45 PM', status: 'completed', isCompletedMorning: true },
      { id: 'stop_2', name: 'Kasanda Market Junction', stopName: 'Kasanda Market Junction', scheduledTime: '07:05 AM', scheduledMorningTime: '07:05 AM', scheduledAfternoonTime: '16:05 PM', status: 'completed', isCompletedMorning: true },
      { id: 'stop_3', name: 'Highridge Post Office', stopName: 'Highridge Post Office', scheduledTime: '07:20 AM', scheduledMorningTime: '07:20 AM', scheduledAfternoonTime: '16:20 PM', status: 'current', isCompletedMorning: false },
      { id: 'stop_4', name: 'Kabwe Tech Main Campus Dropoff', stopName: 'Kabwe Tech Main Campus Dropoff', scheduledTime: '07:35 AM', scheduledMorningTime: '07:35 AM', scheduledAfternoonTime: '16:35 PM', status: 'pending', isCompletedMorning: false },
    ]
  }
];

export const INITIAL_GUARDIAN_PASSES: Record<string, GuardianPickupPass> = {
  'STU-2026-0012': {
    studentNumber: 'STU-2026-0012',
    studentName: 'Chileshe Mwila',
    guardianName: 'Mrs. Gertrude Mwila',
    guardianPhone: '+260 977 123456',
    guardianRelation: 'Mother & Registered Primary Guardian',
    dailySecurityPin: '7492',
    qrVerificationCode: 'KTH-SEC-GATE-PASS-2026-0012-7492',
    validDate: '2026-08-28',
    authorizedByHead: true,
    pickupTimeWindow: '15:30 - 17:15 PM'
  }
};

export const INITIAL_BEHAVIOR_LOGS: StudentBehaviorLog[] = [
  {
    id: 'beh_001',
    studentNumber: 'STU-2026-0012',
    studentName: 'Chileshe Mwila',
    type: 'merit',
    points: 10,
    title: 'Outstanding Physics Practical Experiment Demonstration',
    description: 'Chileshe demonstrated exceptional grasp of Ohm’s Law and circuit resistance in the Physics laboratory, helping peers with calculations.',
    teacherId: 'user_teacher_chanda',
    teacherName: 'Mr. Patrick Chanda',
    subjectName: 'Physics / Integrated Science',
    date: '2026-02-18',
    actionTaken: 'Awarded 10 Merit Points & Academic Commendation Certificate',
    acknowledgedByParent: true,
    parentNotes: 'Thank you Mr. Chanda, we are encouraging Chileshe to keep this up!'
  },
  {
    id: 'beh_002',
    studentNumber: 'STU-2026-0012',
    studentName: 'Chileshe Mwila',
    type: 'homework_excellence',
    points: 5,
    title: 'Flawless Mathematics Algebra Homework Submission',
    description: 'Completed all 15 algebraic factorization problems with clean mathematical steps and no errors.',
    teacherId: 'user_teacher_tembo',
    teacherName: 'Mr. Kelvin Tembo',
    subjectName: 'Mathematics',
    date: '2026-02-22',
    actionTaken: 'Marked 100% and recorded in continuous assessment portfolio.',
    acknowledgedByParent: true
  },
  {
    id: 'beh_003',
    studentNumber: 'STU-2026-0012',
    studentName: 'Chileshe Mwila',
    type: 'attendance_alert',
    points: 0,
    title: 'Punctuality Commendation - 100% On-Time Morning Assembly',
    description: 'Maintained perfect early arrival for 4 consecutive weeks without a single late arrival.',
    teacherId: 'user_teacher_tembo',
    teacherName: 'Mr. Kelvin Tembo',
    date: '2026-02-27',
    acknowledgedByParent: false
  }
];

export const INITIAL_CONFERENCES: ParentTeacherConference[] = [
  {
    id: 'ptc_001',
    studentNumber: 'STU-2026-0012',
    studentName: 'Chileshe Mwila',
    parentId: 'user_parent_mwila',
    parentName: 'Mrs. Gertrude Mwila',
    teacherId: 'user_teacher_tembo',
    teacherName: 'Mr. Kelvin Tembo',
    subjectName: 'Mathematics & Homeroom Advisory',
    date: '2026-03-05',
    timeSlot: '14:30 - 14:50',
    mode: 'zoom_virtual',
    zoomJoinUrl: 'https://zoom.us/j/9928174410?pwd=KABWE',
    topicAgenda: 'Discussing ECZ preparation in Geometry and Continuous Assessment Test 2 readiness.',
    status: 'confirmed',
    teacherNotes: 'Looking forward to discussing Chileshe’s strong trajectory towards a Distinction Grade 1.'
  }
];

export const INITIAL_PERMISSION_SLIPS: PermissionSlip[] = [
  {
    id: 'perm_001',
    title: 'Kafue Gorge Hydropower & Victoria Falls STEM Geography Excursion',
    destination: 'Southern Province (Kafue Gorge & Livingstone)',
    date: '2026-03-18',
    departureTime: '06:00 AM',
    returnTime: '19:00 PM (Next Day)',
    organizingTeacher: 'Mr. Patrick Chanda & Mrs. Lungu',
    gradeTarget: 'Grade 9 & Grade 11',
    costZMW: 650,
    description: 'Educational field study covering hydroelectric generation, turbine mechanics, renewable energy grid integration, and physical geography.',
    emergencyProvisions: 'School First Aid Team, comprehensive passenger transport insurance, school bus convoy with certified drivers.',
    deadlineDate: '2026-03-10',
    signedByParentId: 'user_parent_mwila',
    signedTimestamp: '2026-02-20T11:00:00Z',
    guardianSignatureName: 'Gertrude Mwila',
    medicalConditionsNote: 'No major allergies; carries asthma inhaler as precaution.',
    status: 'signed'
  },
  {
    id: 'perm_002',
    title: 'Lusaka Inter-School National Mathematics & Science Olympiad',
    destination: 'University of Zambia (UNZA Great East Road Campus)',
    date: '2026-04-02',
    departureTime: '07:00 AM',
    returnTime: '17:30 PM',
    organizingTeacher: 'Mr. Kelvin Tembo',
    gradeTarget: 'Grade 9 STEM Representatives',
    costZMW: 200,
    description: 'Chileshe has been selected to represent Kabwe Tech in the Junior Secondary Mathematics Competition.',
    emergencyProvisions: 'Accompanied by 3 faculty members and school vehicle.',
    deadlineDate: '2026-03-25',
    status: 'pending'
  }
];

export const INITIAL_CLINIC_VISITS: HealthClinicVisit[] = [
  {
    id: 'visit_001',
    studentNumber: 'STU-2026-0012',
    studentName: 'Chileshe Mwila',
    visitDate: '2026-02-12',
    time: '11:15 AM',
    reasonForVisit: 'Mild headache during mid-morning double period',
    vitalSigns: {
      temperatureC: 36.8,
      pulseRateBpm: 76,
      bloodPressure: '115/75'
    },
    nurseName: 'Sister Grace Banda (RN - School Clinic)',
    nurseObservations: 'Student was slightly dehydrated after physical education. No fever, normal vitals.',
    treatmentAdministered: 'Administered 500mg Paracetamol, oral rehydration fluid (500ml), rested in sick bay for 30 minutes.',
    actionRecommended: 'returned_to_class',
    parentAlertSent: true
  }
];

export const INITIAL_CANTEEN_WALLETS: Record<string, CanteenWallet> = {
  'STU-2026-0012': {
    studentNumber: 'STU-2026-0012',
    studentName: 'Chileshe Mwila',
    currentBalanceZMW: 185.00,
    dietaryRestrictions: ['Peanut Allergy Warning'],
    dailySpendingLimitZMW: 35.00,
    recentTransactions: [
      { id: 'c_tx_01', date: '2026-02-26', itemDescription: 'Healthy Lunch Meal: Nshima, Grilled Chicken & Vegetables', amount: 25.00, type: 'purchase' },
      { id: 'c_tx_02', date: '2026-02-25', itemDescription: 'Fruit Juice & Mineral Water', amount: 12.00, type: 'purchase' },
      { id: 'c_tx_03', date: '2026-02-20', itemDescription: 'Airtel Money Parent Top-Up', amount: 150.00, type: 'top_up', channel: 'Airtel Money' }
    ]
  }
};



